/* Data Science revision bank, part 3 (revision mode only). Lecture 2: data models, schema, graphs, NoSQL. Concepts only, no SQL syntax, no calculator. Numbers verified with node. */
(function () {
  const B = NIC.bank, Qf = NIC.qfig;
  const M = (q, o, a, why, x = {}) => ({ type: "mcq", q, o, a, why, ...x });
  const TF = (q, yes, why) => ({ type: "mcq", q: `True or false? ${q}`, o: ["True", "False"], a: yes ? 0 : 1, why });

  /* A small ferry network for the pick questions. */
  const PORTS = { A: [60, 130], B: [170, 50], C: [170, 210], D: [290, 130], E: [400, 60], F: [400, 210] };
  const ROUTES = [["A", "B"], ["A", "C"], ["B", "D"], ["C", "D"], ["D", "E"], ["D", "F"], ["E", "F"]];

  B.add("ds-models", [
    M("What does a data model do for an application?", ["It maps the app's objects to a stored form such as tables or JSON", "It copies the app's objects onto extra servers, so a crash never loses any of them", "It scrambles the app's objects so outsiders cannot read them", "It times how long the app's objects take to load"], 0, "A data model is the mapping between an application entity and how a system stores it."),
    TF("An object-relational mapper (ORM) removes any mismatch between objects and tables.", false, "It automates the translation, but the fit is still often unintuitive from the business point of view."),
    { type: "cat", q: "A plant nursery app. Which kind of relationship is each one?", buckets: ["One-to-many", "Many-to-one", "Many-to-many"],
      items: [["One greenhouse holds many plants, each in only that greenhouse", 0], ["Hundreds of plants all come from the same supplier", 1], ["Gardeners follow many gardeners and are followed by many", 2], ["One plant has several care tips that belong only to it", 0]],
      why: "One parent with owned children is one-to-many; many records sharing one entity is many-to-one; links that go both ways in bulk are many-to-many." },
    M("Which is NOT one of the lecture's ways to store a one-to-many list such as a profile's positions?", ["A separate table whose rows carry a foreign key to the user", "A structured JSON or XML column inside the user row", "JSON or XML text kept in a plain text field", "A separate database server that holds one copy per position"], 3, "The three options are normalised tables, a structured column, or text in a field. Adding servers is a scaling tool, not a data model."),
    { type: "match", q: "Match each way of storing a gardener's list of plants to its main trait.", pairs: [["Separate table with a foreign key", "Each row points back to its owner"], ["Structured JSON column", "Nested data can still be indexed and queried"], ["JSON text in a text field", "The database sees only opaque text"]], why: "Normalised rows link by key, a structured column stays queryable, and plain text is opaque to the database." },
    TF("All documents in one collection must have exactly the same fields.", false, "Documents in a single store can differ from one another; that flexibility is the point."),
    M("Which of these is an example of a document database?", ["CouchDB", "Cassandra", "DynamoDB", "PostgreSQL"], 0, "CouchDB, MongoDB and Firestore are the lecture's document stores. Cassandra is wide-column, DynamoDB key-value, PostgreSQL relational."),
    M("Why do document models handle many-to-many links badly?", ["Shared data is copied into many documents, or joined with clumsy support", "Documents cannot hold more than one link, so each needs its own file", "Documents forget their links whenever the database restarts or is moved to a new machine", "Every link forces the whole collection to be locked while it is read"], 0, "Without good joins, the same data is either duplicated or fetched by slower, more complicated join features."),
    { type: "multi", q: "Which are genuine advantages of the relational model over the document model? Select all that apply.", o: ["Better support for joins", "Better support for many-to-one and many-to-many links", "All of an object's data is stored together in one place", "Documents in the same table can each have different fields"], a: [0, 1],
      why: "Locality and flexible fields are the document model's strengths. Joins and shared entities are where relational wins." },
    { type: "order", q: "Put the steps in order for storing a user's list of positions in normalised tables.", items: ["Give each user row a unique ID", "Create a separate table for the positions", "Add a column that holds the owner's user ID", "Insert one row per position"], why: "The ID must exist first, then a child table with a foreign key column, then one row per item." },
    M("Why is translating between objects and tables \"not always intuitive\"?", ["Objects nest and link freely, but rows are flat and joined by keys", "Objects are stored on disk while tables live only in memory", "Objects can only hold numbers, while tables are the only place that can hold any text", "Objects change each time they are read, but tables never change"], 0, "One nested object may need several tables and joins to rebuild, which is awkward to reason about."),
    M("\"Semi-structured\" documents such as JSON mean the data…", ["carries its own labels, but needs no fixed table layout", "has no labels at all, so it is only ever stored as raw text", "must match one shared layout before it can be saved", "is split into rows and columns the moment it arrives"], 0, "Keys label the values inside each document, without a rigid schema imposed from outside."),
    TF("In a normalised design, a profile's positions live in rows that point back to the profile with a foreign key.", true, "That is the definition of the normalised one-to-many representation."),
    M("Three gardeners list 5, 2 and 4 plants. How many rows does the separate plants table hold?", ["3", "11", "33", "40"], 1, "One row per plant: 5 + 2 + 4 = 11. The three gardeners are rows in a different table.", { hint: "One row per plant, so add the three counts: 5 + 2 + 4." }),
  ]);

  B.add("ds-schema", [
    M("Schema-on-read is closest to which idea from programming?", ["Dynamic typing: the shape is checked when the data is used", "Static typing: the shape is checked before the program runs", "Garbage collection: unused data is cleaned up later", "Compiling: the data is turned into machine code first"], 0, "Neither side checks the shape up front; the code that reads the data deals with whatever it finds."),
    { type: "match", q: "Match each term to its meaning.", pairs: [["Schema-on-write", "Structure enforced when data is stored"], ["Schema-on-read", "Structure interpreted when the app reads it"], ["Locality", "An object's data sits together in one place"], ["Heterogeneous data", "Different kinds of object in one collection"]], why: "Write-time versus read-time structure, plus the storage layout and data variety that go with them." },
    TF("Most document databases reject a document that is missing a field.", false, "Most enforce no schema at all, so no field is guaranteed."),
    { type: "cat", q: "Which data suits which approach?", buckets: ["Schema-on-read", "Schema-on-write"],
      items: [["A catalogue where each product type has very different attributes", 0], ["Partner feeds whose format you do not control", 0], ["A ledger where every row must have an amount and a date", 1], ["A payroll table whose fixed columns every report relies on", 1]],
      why: "Varied or uncontrolled data favours flexible reading. Data with rules that must always hold favours an enforced schema." },
    M("A weather startup replaces a \"location\" field with separate \"lat\" and \"lon\" fields in a document store. Old documents keep the old field. How should the reading code cope?", ["Test which fields exist and convert the old one when needed", "Refuse to read any document that still has the old field", "Wait until every stored document has been rewritten into the new shape first", "Assume every document already has the new fields"], 0, "Schema-on-read means the application handles both shapes as it reads."),
    M("A hotel booking page always shows the guest, room, extras and notes for one booking together. How does locality help?", ["One read fetches the whole booking, not several tables", "The booking is copied to a second server to spread the load", "The guest's name is stored once and shared by every booking", "The extras are sorted alphabetically before they are shown"], 0, "The document is stored as one continuous piece, so one request brings everything back."),
    TF("Locality is something only document databases can offer.", false, "Google Spanner offers it in a relational model, and wide-column stores manage it with column families."),
    { type: "multi", q: "When does schema-on-read help most? Select all that apply.", o: ["Different kinds of object share one collection", "You do not control the structure of incoming data, such as tweets", "Every record must be checked before it is ever saved", "Every field must have the same type in all records"], a: [0, 1],
      why: "Heterogeneous data and data you cannot control need a tolerant reader. Strict pre-save checks call for schema-on-write." },
    { type: "order", q: "Put the steps in order for splitting one \"full name\" column into first and last names in a relational database.", items: ["Alter the table to add first-name and last-name columns", "Update every existing row to fill the new columns", "Deploy code that reads the new columns"], why: "The columns must exist before they can be filled, and the app switches over once the data is ready." },
    M("What is the main downside of having no schema at all?", ["No guarantee which fields a given document contains", "The database can no longer store more than one document", "Every document must be read twice before it is used", "Documents have to be written in alphabetical order"], 0, "Your code cannot assume a field exists, so it must check the shape itself."),
    { type: "slider", q: "A table has 200 million rows. Filling in a new column updates 2 million rows every minute. About how many minutes does the update run?", min: 0, max: 300, step: 10, ans: 100, tol: 20, unit: " min", hint: "200 million ÷ 2 million per minute.", why: "200 ÷ 2 = 100 minutes, which is why large relational changes can need downtime." },
    M("A schema that is \"implicit\" in a document store lives…", ["in the application code that reads the documents", "in a rulebook the database checks before saving", "in the file name of each document", "in an index that is rebuilt every night"], 0, "Nothing in the store enforces it; the reading code carries the assumptions."),
    { type: "bug", q: "This reader should return a full name from new documents (first_name and last_name) or old ones (name). Click the faulty line.", code: ["def full_name(doc):", "    if \"first_name\" in doc:", "        return doc[\"first_name\"] + \" \" + doc[\"last_name\"]", "    return doc[\"first_name\"]"], a: 3, why: "Old documents have no first_name field. The fallback should read doc[\"name\"]." },
  ]);

  B.add("ds-graph", [
    M("Which kind of problem is naturally easy for a graph model but awkward for tables or documents?", ["Many-to-many links followed for several hops", "Storing a single long list of monthly totals", "Keeping one large text document for each author", "Counting how many rows a table currently holds"], 0, "Graphs make relationships the first-class thing, so hopping along them is direct."),
    { type: "cat", q: "In a ferry network, is each item a vertex or an edge?", buckets: ["Vertex (node)", "Edge"],
      items: [["A port", 0], ["A ferry route between two ports", 1], ["A passenger in a social network", 0], ["A \"follows\" link between two passengers", 1]],
      why: "Entities are vertices; the relationships between them are edges." },
    { type: "match", q: "Match each property-graph part to its role.", pairs: [["Unique ID", "Identifies one vertex or edge"], ["Incoming and outgoing edges", "Let you hop to neighbouring vertices"], ["Key-value properties", "Hold extra facts such as a name or a date"], ["Relationship label", "Says what kind of link an edge is"]], why: "IDs identify, edges connect, properties describe, labels classify the relationship." },
    { type: "pick", q: "<b>Click the port with the most routes attached to it.</b>", fig: Qf.graph(PORTS, ROUTES, { pick: "nodes", w: 460, h: 260 }), a: ["D"], why: "D has four routes (to B, C, E and F). Every other port has two." },
    { type: "pick", q: "<b>Click every route that touches port E.</b>", fig: Qf.graph(PORTS, ROUTES, { pick: "edges", w: 460, h: 260 }), a: ["D-E", "E-F"], why: "E connects to D and to F. Those are its only two routes." },
    M("A property graph can be viewed as two relational tables. What do they hold?", ["Vertices in one table and edges in the other", "Reads in one table and writes in the other", "Old records in one table and new records in the other", "Names in one table and numbers in the other"], 0, "One table lists the vertices with their properties; the other lists the edges with their head, tail, label and properties."),
    TF("In a property graph, any vertex may be connected to any other vertex.", true, "There is no restriction on which vertices can be linked; labels say what each link means."),
    { type: "match", q: "Match each graph technique to what it does.", pairs: [["Dijkstra", "Finds the shortest route across a road network"], ["PageRank", "Scores how relevant a web page is for a search"], ["Traversal", "Hops along edges from a starting vertex"]], why: "Dijkstra and PageRank are the lecture's ready-made graph algorithms; traversal is the basic operation they build on." },
    M("A hospital records which doctors refer patients to which specialists, and wants everyone within three referrals of one doctor. Why fit a graph?", ["Each vertex leads straight to its edges, so hops are cheap to follow", "Graphs store every doctor's name only once on a single server", "Graphs stop two doctors from ever sharing the same specialist", "Graphs keep every referral in one sorted list on disk"], 0, "Given a vertex you can quickly find its incoming and outgoing edges, so repeated hops stay easy."),
    { type: "multi", q: "Which datasets are naturally graphs? Select all that apply.", o: ["A road network of junctions and roads", "Web pages linked to other pages", "A social network of people and friendships", "A list of 10,000 temperature readings"], a: [0, 1, 2],
      why: "Roads, links and friendships are entities joined by relationships. A plain list of readings has no links between items." },
    { type: "order", q: "Put the steps in order for a two-hop trip starting at vertex A.", items: ["Start at vertex A", "Read A's outgoing edges", "Move to one of A's neighbours", "Read that neighbour's outgoing edges"], why: "Each hop is: read the edges of where you are, then move along one of them." },
    TF("Different edge labels let one graph represent many different kinds of relationship.", true, "Labels such as \"follows\" or \"works at\" sit on edges, so one graph can mix relationships."),
    M("In a property graph, where would you store \"friends since 2019\"?", ["As a property on the friendship edge", "As a property on the first friend's vertex only", "In a separate document for the year 2019", "In the ID of the second friend's vertex"], 0, "A fact about the relationship belongs on the edge that represents it."),
    TF("To find a vertex's neighbours in a graph, you must scan every edge in the graph.", false, "A vertex keeps its own incoming and outgoing edges, so its neighbours are found directly."),
  ]);

  B.add("ds-nosql", [
    { type: "cat", q: "Which NoSQL family does each product belong to?", buckets: ["Document", "Key-value", "Wide-column"],
      items: [["MongoDB", 0], ["Firestore", 0], ["DynamoDB", 1], ["Cassandra", 2], ["CouchDB", 0]],
      why: "MongoDB, Firestore and CouchDB are document stores; DynamoDB is key-value; Cassandra is wide-column." },
    M("In the lecture's sense, NoSQL databases are…", ["non-relational stores that favour simple design and scaling out", "relational stores that have no query language and no way to search", "databases that only run on a single powerful server", "old formats that were replaced by spreadsheets"], 0, "The label means non-relational storage and retrieval, with simplicity, scalability and availability as priorities."),
    M("In MongoDB, what sits directly inside a database?", ["Collections of documents", "One giant table shared by every document", "Foreign-key rules linking every document", "A property graph of all the documents"], 0, "Databases hold collections, and collections hold documents."),
    TF("A wide-column store requires every row to use exactly the same column names.", false, "Column names and formats can vary from record to record."),
    M("A session store must get, set and expire a shopping basket by its session ID, millions of times a second. Which family fits best?", ["Key-value", "Graph", "Wide-column", "Relational with many joins"], 0, "Every access is by one exact key, which is what key-value stores do best."),
    { type: "match", q: "Match each scaling term to its meaning.", pairs: [["Horizontal scaling", "Adding more machines to share the load"], ["Vertical scaling", "Moving to one bigger machine"], ["Availability", "The service keeps answering requests"]], why: "NoSQL systems lean on horizontal scaling and availability." },
    { type: "multi", q: "Which of these are NoSQL families in the lecture? Select all that apply.", o: ["Document", "Key-value", "Wide-column", "Graph", "Fixed-schema table store"], a: [0, 1, 2, 3],
      why: "The lecture lists document, key-value, wide-column and graph. A fixed-schema table store is the relational approach." },
    { type: "order", q: "Put MongoDB's building blocks in order, from smallest to largest.", items: ["A field with a value", "A document", "A collection", "A database"], why: "Fields make up a document, documents fill a collection, collections live in a database." },
    M("A museum catalogue keeps rows in named columns, but paintings, coins and fossils each need different columns. Which family fits?", ["Wide-column", "Key-value", "Graph", "Fixed-schema tables"], 0, "Wide-column stores use tables and rows, with column names that can vary per record."),
    TF("A graph database counts as one of the NoSQL families.", true, "Graph is the fourth family, alongside document, key-value and wide-column."),
    M("A ticketing app saves each event with its venue, price tiers and a nested seat map, and always loads it whole. Which family fits?", ["Document", "Key-value", "Graph", "Wide-column"], 0, "Self-contained nested records that are read together are the document model's home ground."),
    M("A rail planner wants the fewest changes between two stations across a web of lines. Which family fits?", ["Graph", "Key-value", "Document", "Wide-column"], 0, "Stations are vertices and lines are edges, so route finding follows edges directly."),
    { type: "slider", q: "Each server handles 20,000 requests a second and the peak load is 100,000 requests a second. About how many servers share the peak?", min: 0, max: 12, step: 1, ans: 5, tol: 1, unit: " servers", hint: "How many 20,000s fit into 100,000?", why: "100,000 ÷ 20,000 = 5 servers, the scale-out idea behind NoSQL." },
    M("DynamoDB's \"complex primary key\" combines…", ["a partition key plus a sort key", "a graph edge plus a vertex ID", "a table name plus a column name", "a document ID plus a collection name"], 0, "The two-part key lets items be grouped by one part and ordered by the other."),
  ]);
})();
