/* NIC revision bank, visual and varied questions, part 3.
   Lecture 4 (selection, replacement, mutation, crossover, the lab). Every figure is needed to answer. */
(function () {
  const B = NIC.bank;
  const FONT = "font:800 13px var(--sans)";
  const txt = (x, y, s, o = {}) => `<text x="${x}" y="${y}" text-anchor="${o.a || "middle"}" style="font:${o.w || 800} ${o.s || 13}px var(--sans);fill:${o.c || "var(--text)"}">${s}</text>`;

  /* Bar chart. vals: numbers; ids: data-pick ids (optional); labels under bars; line: {y, label} horizontal marker. */
  function bars(vals, { ids = null, labels = null, max = null, w = 520, h = 210, line = null, colors = null, show = true, inside = false, fmt = (v) => v } = {}) {
    const m = max || Math.max(...vals) * 1.1, n = vals.length, bw = Math.min(54, (w - 40) / n - 12), gap = (w - 40) / n;
    const Y = (v) => h - 34 - (v / m) * (h - 66);
    const body = vals.map((v, i) => {
      const x = 20 + gap * i + (gap - bw) / 2;
      const r = `<rect x="${x}" y="${Y(v)}" width="${bw}" height="${h - 34 - Y(v)}" rx="6" fill="${colors ? colors[i] : "var(--blue)"}" stroke="var(--line-2)" stroke-width="2" fill-opacity=".85"/>`;
      const val = show ? (inside ? txt(x + bw / 2, h - 44, fmt(v), { s: 12, c: "#fff" }) : txt(x + bw / 2, Y(v) - 6, fmt(v), { s: 12 })) : "";
      const lab = labels ? txt(x + bw / 2, h - 14, labels[i]) : "";
      return ids ? `<g data-pick="${ids[i]}">${r}${val}${lab}</g>` : `<g>${r}${val}${lab}</g>`;
    }).join("");
    const ln = line ? `<line x1="14" x2="${w - 10}" y1="${Y(line.y)}" y2="${Y(line.y)}" stroke="var(--rose)" stroke-width="3" stroke-dasharray="7 5"/>${txt(w - 12, Y(line.y) - 6, line.label, { a: "end", c: "var(--rose-ink)" })}` : "";
    return `<svg viewBox="0 0 ${w} ${h}" style="max-height:${h}px"><line x1="14" x2="${w - 10}" y1="${h - 34}" y2="${h - 34}" stroke="var(--line-2)" stroke-width="2"/>${body}${ln}</svg>`;
  }

  /* A row of genes. cells: [text, colour]. */
  function strip(cells, x, y, { cw = 34, ch = 34 } = {}) {
    return cells.map((c, i) => `<rect x="${x + i * cw}" y="${y}" width="${cw - 3}" height="${ch}" rx="6" fill="${c[1] || "var(--panel)"}" stroke="var(--line-2)" stroke-width="2"/>${txt(x + i * cw + (cw - 3) / 2, y + ch / 2 + 5, c[0], { c: c[2] || "var(--text)" })}`).join("");
  }

  /* Pie wheel. vals, labels; ids optional (pick). */
  function pie(vals, labels, cx, cy, r, ids, cols) {
    const tot = vals.reduce((a, b) => a + b, 0); let a0 = -Math.PI / 2;
    return vals.map((v, i) => {
      const a1 = a0 + (v / tot) * Math.PI * 2, big = a1 - a0 > Math.PI ? 1 : 0;
      const p = `M${cx} ${cy} L${(cx + r * Math.cos(a0)).toFixed(1)} ${(cy + r * Math.sin(a0)).toFixed(1)} A${r} ${r} 0 ${big} 1 ${(cx + r * Math.cos(a1)).toFixed(1)} ${(cy + r * Math.sin(a1)).toFixed(1)} Z`;
      const mid = (a0 + a1) / 2, lx = cx + r * 0.66 * Math.cos(mid), ly = cy + r * 0.66 * Math.sin(mid);
      a0 = a1;
      const g = `<path d="${p}" fill="${cols[i]}" fill-opacity=".75" stroke="var(--panel)" stroke-width="3"/>${txt(lx, ly + 5, labels[i], { s: 13 })}`;
      return ids ? `<g data-pick="${ids[i]}">${g}</g>` : `<g>${g}</g>`;
    }).join("");
  }

  /* ---------- l4-types ---------- */
  const bestRun = [0.62, 0.70, 0.70, 0.66, 0.74, 0.78];
  const typesFig = () => {
    const w = 520, h = 210, X = (i) => 50 + i * 82, Y = (v) => h - 40 - ((v - 0.55) / 0.3) * (h - 80);
    const path = bestRun.map((v, i) => `${i ? "L" : "M"}${X(i)} ${Y(v)}`).join(" ");
    const dots = bestRun.map((v, i) => `<g data-pick="G${i + 1}"><circle cx="${X(i)}" cy="${Y(v)}" r="13" fill="var(--panel)" stroke="var(--line-2)" stroke-width="3"/>${txt(X(i), Y(v) + 4, v.toFixed(2), { s: 10 })}</g>`).join("");
    const lab = bestRun.map((_, i) => txt(X(i), h - 14, "Gen " + (i + 1), { s: 12, c: "var(--text-dim)" })).join("");
    return `<svg viewBox="0 0 ${w} ${h}" style="max-height:${h}px"><line x1="20" x2="${w - 10}" y1="${h - 30}" y2="${h - 30}" stroke="var(--line-2)" stroke-width="2"/>${txt(18, 16, "Best fitness in the population (maximising)", { a: "start", c: "var(--text-dim)" })}<path d="${path}" fill="none" stroke="var(--teal)" stroke-width="3"/>${dots}${lab}</svg>`;
  };
  B.add("l4-types", [
    { type: "pick", q: "This GA logged its best fitness each generation. Tap the generation that proves the run cannot be elitist.", fig: typesFig(), a: "G4", why: "Elitism copies the best individuals unchanged, so the best fitness can never fall. It dips from 0.70 to 0.66 at generation 4, so the best was lost. Staying level (generation 3) is allowed." },
    { type: "cat", q: "Which scheme suits each situation better?", buckets: ["Generational", "Steady-state"], items: [["Fitness is scored on 200 machines at once, and the whole batch finishes together", 0], ["Memory is so tight that only one child can exist at a time", 1], ["A lucky good child should start breeding straight away", 1], ["You want a big change to the population in a single step (more exploration)", 0], ["The old population should be swapped for a new one in one go", 0], ["Each step should be cheap, so you can stop at any moment with a usable population", 1]], why: "Generational schemes make a whole batch of children and swap them in together, which suits parallel scoring and larger jumps. Steady-state changes one or two members at a time, so it needs little memory, uses good children at once and can stop any time." },
    { type: "order", q: "Put one generation of an elitist generational GA in the right order.", items: ["Copy the 2 best individuals into the new population", "Pick parents from the old population", "Apply crossover and mutation to make children", "Fill the new population with the children and drop the old one"], why: "The elites are set aside first so nothing can damage them. Parents are chosen from the old population, children are made from them, and then the old population is replaced by elites plus children." },
    { type: "slider", q: "Generational GA: population 20, elitism keeps 2, run for 25 generations. A steady-state GA makes one child per step. How many steady-state steps make the same number of children?", min: 100, max: 800, step: 50, ans: 450, tol: 50, unit: " steps", hint: "Each generation makes 20 − 2 = 18 children. And 18 × 25 = 18 × 100 ÷ 4 = 450.", why: "Elites are copied, not made, so each generation creates 18 children. 18 × 25 = 450, so 450 steady-state steps cost the same number of evaluations. Compare schemes on evaluations, not on generations." },
    { type: "bug", q: "This steady-state step is meant to replace the weakest member (maximising). Tap the faulty line.", code: ["parent = tournament(pop, 3)", "child = mutate(copy(parent))", "slot = index_of_highest_fitness(pop)", "if fitness(child) >= fitness(pop[slot]):", "    pop[slot] = child"], a: 2, why: "It looks for the member with the highest fitness, which is the best. The child would overwrite the best, so the scheme would throw away its champion. It should look for the lowest fitness." },
  ]);

  /* ---------- l4-replacement ---------- */
  const popBars = (vals, o) => bars(vals, Object.assign({ max: 1, labels: vals.map((_, i) => "Slot " + (i + 1)), fmt: (v) => v.toFixed(2) }, o));
  const snap = (vals, title, x0) => {
    const bw = 24, g = 30;
    return txt(x0, 18, title, { a: "start", s: 15 }) + vals.map((v, i) => `<rect x="${x0 + i * g}" y="${150 - v * 120}" width="${bw}" height="${v * 120}" rx="4" fill="var(--blue)" fill-opacity=".85" stroke="var(--line-2)" stroke-width="2"/>${txt(x0 + i * g + bw / 2, 166, v.toFixed(2).slice(1), { s: 9, c: "var(--text-dim)" })}`).join("");
  };
  B.add("l4-replacement", [
    { type: "pick", q: "A child with fitness 0.55 is about to be inserted. Replace-first-weaker could overwrite any member weaker than the child, depending on the scan. Tap every slot that is a candidate.", fig: popBars([0.7, 0.5, 0.9, 0.3, 0.6, 0.2], { inside: true, ids: ["s1", "s2", "s3", "s4", "s5", "s6"], line: { y: 0.55, label: "child 0.55" }, max: 1.1 }), a: ["s2", "s4", "s6"], why: "A slot is a candidate only if its fitness is below 0.55: slots 2 (0.50), 4 (0.30) and 6 (0.20). Scanning from slot 1 picks slot 2, whereas replace-weakest always takes slot 6." },
    { type: "cat", q: "Which strategy does each statement describe?", buckets: ["Replace weakest only", "Replace first weaker only", "Both"], items: [["Looks at every member before deciding", 0], ["Can stop as soon as it meets a weaker member", 1], ["Which member goes depends on the order of the slots", 1], ["Rejects a child that is worse than every member", 2], ["The best fitness in the population can never go down", 2], ["Always overwrites the member with the lowest fitness", 0]], why: "Replace weakest is a full scan with a fixed target. Replace first weaker stops early and depends on slot order. Both refuse a child that beats nobody, and both keep the best fitness from falling, because a child only replaces a weaker member (or an equal one)." },
    { type: "mcq", q: "The same stream of children was fed into two populations of 8, one using replace-weakest and one using replace-first-weaker. Both have the same best member now. Which snapshot is replace-weakest, and why?", fig: `<svg viewBox="0 0 520 190" style="max-height:190px">${snap([0.82, 0.85, 0.88, 0.84, 0.9, 0.86, 0.83, 0.87], "Snapshot X", 12)}${snap([0.9, 0.35, 0.8, 0.5, 0.88, 0.2, 0.75, 0.6], "Snapshot Y", 272)}</svg>`, o: ["X: always removing the worst lifts the floor quickly", "Y: always removing the worst leaves a wide spread", "X: weak members get time to survive, so scores bunch up", "Y: weak members get time to survive, so low scores linger"], a: 0, why: "Replace-weakest is greedy: every accepted child deletes the current floor, so the low scores disappear and the spread shrinks (X). Replace-first-weaker lets some weak members sit in slots the scan rarely reaches, so low scores linger (Y). That is also why it keeps more diversity." },
    { type: "slider", q: "A population of 1000 sits in no particular order, and about half of the members are weaker than the new child. Replace-first-weaker scans from a start slot. About how many members does it look at before it stops?", min: 0, max: 10, step: 1, ans: 2, tol: 1, unit: " looks", hint: "Each look is a coin flip: weaker (stop) or not (carry on). How many coin flips until the first heads?", why: "With a 50% chance of a weaker member at every slot, you expect to stop after about 2 looks. Replace-weakest must always look at all 1000, which is why first-weaker is cheaper." },
    { type: "bug", q: "This should find the weakest member (maximising) so the child can replace it. Tap the faulty line.", code: ["w = 0", "for i in range(1, P):", "    if fit[i] > fit[w]: w = i", "if child_fit >= fit[w]:", "    pop[w] = child"], a: 2, why: "The comparison is the wrong way round, so w ends up as the index of the best member and the child would replace the champion. It must use fit[i] < fit[w] to track the lowest fitness." },
  ]);

  /* ---------- l4-pressure ---------- */
  const panel = (id, x0, best, mean, title) => {
    const X = (i) => x0 + 10 + i * (150 / (best.length - 1)), Y = (v) => 150 - v * 110;
    const L = (a, c) => `<path d="${a.map((v, i) => `${i ? "L" : "M"}${X(i).toFixed(1)} ${Y(v).toFixed(1)}`).join(" ")}" fill="none" stroke="${c}" stroke-width="3" stroke-linecap="round"/>`;
    return `<g data-pick="${id}"><rect x="${x0}" y="24" width="170" height="140" rx="10" fill="var(--panel)" stroke="var(--line-2)" stroke-width="2"/>${L(mean, "var(--blue)")}${L(best, "var(--teal)")}</g>${txt(x0 + 85, 16, title, { s: 14 })}`;
  };
  const pressFig = `<svg viewBox="0 0 560 215" style="max-height:215px">${
    panel("A", 4, [0.3, 0.33, 0.31, 0.35, 0.34, 0.37, 0.36, 0.38], [0.28, 0.3, 0.29, 0.3, 0.31, 0.3, 0.32, 0.31], "Run A") +
    panel("B", 194, [0.3, 0.55, 0.7, 0.72, 0.72, 0.72, 0.72, 0.72], [0.28, 0.4, 0.55, 0.65, 0.7, 0.72, 0.72, 0.72], "Run B") +
    panel("C", 384, [0.3, 0.4, 0.52, 0.62, 0.72, 0.8, 0.86, 0.9], [0.27, 0.34, 0.42, 0.5, 0.58, 0.66, 0.72, 0.78], "Run C")
  }<rect x="190" y="190" width="14" height="5" fill="var(--teal)"/>${txt(210, 196, "best", { a: "start", s: 12 })}<rect x="270" y="190" width="14" height="5" fill="var(--blue)"/>${txt(290, 196, "mean", { a: "start", s: 12 })}${txt(280, 212, "x axis: generations, y axis: fitness", { s: 11, c: "var(--text-faint)" })}</svg>`;
  B.add("l4-pressure", [
    { type: "pick", q: "Three runs of the same EA, differing only in selection pressure. Tap the run that shows premature convergence.", fig: pressFig, a: "B", why: "In run B the mean climbs until it meets the best and both go flat at 0.72: everyone is nearly identical, so selection has nothing left to choose between. Run A barely moves (too little pressure) and run C improves steadily with a healthy gap between best and mean." },
    { type: "cat", q: "How does each change affect selection pressure?", buckets: ["Raises pressure", "Lowers pressure", "No change"], items: [["Tournament size 3 becomes 8", 0], ["Tournament size 6 becomes 2", 1], ["Replace every fitness by its square (all values positive) in tournament selection", 2], ["Add 1000 to every fitness in roulette selection", 1], ["Subtract the smallest fitness from every fitness in roulette selection", 0], ["Add 1000 to every fitness in tournament selection", 2]], why: "Tournaments only compare, so squaring or shifting fitness keeps the same order and the same pressure. Roulette uses sizes: adding a constant flattens the slices (lower pressure), subtracting the minimum widens the gaps (higher pressure). A bigger tournament means the winner is better on average." },
    { type: "slider", q: "A population of 64 uses tournaments of size 2 and nothing else (no mutation, no crossover). Early on, the best individual's copies roughly double each generation. Starting from 1 copy, about how many generations until the whole population is copies of it?", min: 0, max: 12, step: 1, ans: 6, tol: 1, unit: " generations", hint: "1, 2, 4, 8, 16, 32, 64: count the doublings.", why: "A tournament of size 2 picks the best about twice as often as a random pick, so its copies roughly double each generation: 1 to 64 takes 6 doublings. A bigger tournament would take over faster, which is the high-pressure end of the dial." },
    { type: "multi", q: "Which observations suggest selection pressure is too HIGH?", o: ["The mean fitness is within 1% of the best by generation 10", "The number of distinct genomes falls to 1 by generation 12", "The best creeps up slowly while the mean barely moves", "Almost every child descends from the same two parents", "Best and mean wander up and down with no trend"], a: [0, 1, 3], why: "Mean meeting the best, a single genome and a family tree with only two parents all show that diversity has collapsed. A slow creep and aimless wandering are the signs of too little pressure." },
    { type: "mcq", q: "The three runs below differ only in tournament size. What do they support?", fig: `<table class="t"><tr><th>Run</th><th>Tournament size</th><th>Population identical at…</th><th class="num">Final best</th></tr><tr><td>1</td><td>2</td><td>never (100 gens)</td><td class="num">0.93</td></tr><tr><td>2</td><td>7</td><td>generation 6</td><td class="num">0.71</td></tr><tr><td>3</td><td>1</td><td>never (100 gens)</td><td class="num">0.52</td></tr></table>`, o: ["A moderate size beat both extremes here", "A larger size always gives a better final result", "Size 1 is best because diversity never collapses", "Tournament size has no real effect on the result"], a: 0, why: "Size 7 collapsed diversity early and stalled at 0.71. Size 1 is random choice, so diversity stays but nothing improves. Size 2 kept diversity and still made progress. That is the sweet spot idea: some pressure, not too much." },
  ]);

  /* ---------- l4-roulette ---------- */
  const cols4 = ["var(--teal)", "var(--blue)", "var(--amber)", "var(--violet)"];
  const wheelFig = `<svg viewBox="0 0 520 250" style="max-height:250px">${txt(130, 18, "Fitnesses", { s: 15 })}${pie([4, 3, 2, 1], ["A 4", "B 3", "C 2", "D 1"], 130, 135, 100, null, cols4)}${txt(390, 18, "After adding 20 to every fitness", { s: 15 })}${pie([24, 23, 22, 21], ["A 24", "B 23", "C 22", "D 21"], 390, 135, 100, ["A", "B", "C", "D"], cols4)}</svg>`;
  B.add("l4-roulette", [
    { type: "pick", q: "The left wheel uses raw fitness. The right wheel adds 20 to every fitness. Tap the individual whose slice grew the most.", fig: wheelFig, a: "D", why: "Raw shares are 40%, 30%, 20% and 10%. After adding 20 they are 24/90, 23/90, 22/90 and 21/90, about 27%, 26%, 24% and 23%. D more than doubles its share (10% to 23%) while A shrinks. Adding a constant flattens roulette, so the exact numbers matter." },
    { type: "slider", q: "Five individuals have fitness 1, 1, 1, 1 and 6. In 30 roulette spins, about how many picks go to the four weak individuals combined?", min: 0, max: 30, step: 2, ans: 12, tol: 4, unit: " picks", hint: "The total is 10, so the four weak ones own 4 out of 10 of the wheel. Then 4/10 of 30 = 12.", why: "The weak four own 4 of the 10 units of wheel, a 40% share, so about 12 of 30 spins. Even weak individuals keep a real chance, which is what stops roulette from being pure greed." },
    { type: "order", q: "Put the steps of one roulette selection in order, for a problem where shorter tours are better.", items: ["Turn each tour length into a fitness (for example 1 divided by length)", "Add the fitnesses to get the total size of the wheel", "Draw a random point between 0 and the total", "Walk along the individuals, adding their slices, until the running sum passes the point", "Return the individual whose slice you stopped in"], why: "Roulette needs larger-is-better fitness, so the tour lengths are converted first. After that the wheel is a running sum: a random point is located by adding slices until you pass it." },
    { type: "bug", q: "This roulette spin should favour individuals with bigger fitness. Tap the faulty line.", code: ["total = sum(ind.fit for ind in pop)", "r = random() * total", "running = 0", "for ind in pop:", "    running += ind.fit", "    if running < r:", "        return ind", "return pop[-1]"], a: 5, why: "The test should be running >= r (or >), meaning the point lies inside this slice. With < the loop returns the first individual whenever its slice is smaller than the point, so selection ignores the sizes and favours slot order." },
    { type: "cat", q: "Can this score be fed into roulette as it is?", buckets: ["Use directly", "Transform first"], items: [["Fraction of pixels that match the target (0 to 1)", 0], ["Profit per run, which is sometimes a loss", 1], ["Tour length in km, shorter is better", 1], ["Distance travelled by a robot in metres, longer is better, never negative", 0], ["Number of rule violations, fewer is better", 1], ["Quiz score out of 100, higher is better", 0]], why: "Roulette needs non-negative scores where bigger means better. Losses give negative slices, and anything where smaller is better would favour the worst solutions, so those need converting (shift, or use 1/x or max minus x)." },
  ]);

  /* ---------- l4-rank ---------- */
  B.add("l4-rank", [
    { type: "pick", q: "Linear rank selection with these five individuals. Tap the one that has a 20% chance of being picked.", fig: bars([9, 40, 7, 22, 15], { ids: ["A", "B", "C", "D", "E"], labels: ["A", "B", "C", "D", "E"], max: 48 }), a: "E", why: "Sort by fitness: B 40 is rank 5, D 22 is rank 4, E 15 is rank 3, A 9 is rank 2, C 7 is rank 1. The ranks add up to 15, so rank 3 gives 3/15 = 20%." },
    { type: "order", q: "Population of 4 where lower cost is better, using linear rank selection. Put the individuals from MOST likely to be picked to LEAST likely.", items: ["Cost 7", "Cost 12", "Cost 25", "Cost 40"], why: "When minimising, rank the other way: the lowest cost gets the top rank. Cost 7 gets rank 4 (40%), then 12 (30%), 25 (20%) and 40 (10%)." },
    { type: "cat", q: "Which selection method does each statement describe?", buckets: ["Roulette only", "Rank only", "Both"], items: [["Adding 50 to every fitness changes the probabilities", 0], ["Needs the population sorted first", 1], ["One superfit individual can take almost the whole wheel", 0], ["Multiplying every fitness by 10 changes nothing", 2], ["Probabilities depend only on the order of the individuals", 1], ["Two individuals whose fitness differs by 0.001 can get quite different chances", 1]], why: "Roulette depends on the sizes of fitness values, so shifting breaks it and a giant value takes over, yet scaling everything by the same factor leaves shares alone. Rank uses only order, so shifts and giants do not matter, but it also exaggerates tiny gaps." },
    { type: "mcq", q: "Linear rank selection on 6 individuals (ranks 1 to 6, total 21). How do the selection-probability gaps compare for the pair 10 vs 9.9 and the pair 9.8 vs 1?", fig: bars([10, 9.9, 9.8, 1, 0.9, 0.8], { labels: ["#1", "#2", "#3", "#4", "#5", "#6"], max: 12 }), o: ["Equal: each pair is one rank step apart", "Larger for 9.8 vs 1 because the fitness gap is bigger", "Larger for 10 vs 9.9 because leaders matter more", "Unknown without the total fitness of the population"], a: 0, why: "Rank selection ignores the size of fitness gaps. 10 and 9.9 are ranks 6 and 5; 9.8 and 1 are ranks 4 and 3. Each pair differs by one rank, which is 1/21 of the wheel in both cases. That is a strength against giants and a weakness when gaps really matter." },
    { type: "bug", q: "This should give the BEST individual the biggest slice under linear rank selection. Tap the faulty line.", code: ["order = sorted(pop, key=lambda x: x.fit, reverse=True)   # best first", "for i, ind in enumerate(order):", "    ind.rank = i + 1", "total = P * (P + 1) / 2", "probs = [ind.rank / total for ind in order]"], a: 2, why: "The list is sorted best first, so i = 0 is the best, and rank = i + 1 gives the best rank 1, the smallest slice. The best must get rank P, for example rank = P - i." },
  ]);

  /* ---------- l4-tournament ---------- */
  const chartFig = (vals, title) => {
    const ids = ["Best", "2nd", "3rd", "4th", "Worst"];
    return `<svg viewBox="0 0 520 190" style="max-height:190px">${txt(260, 16, title, { s: 14 })}${vals.map((v, i) => {
      const x = 30 + i * 96, hh = v * 1.9;
      return `<rect x="${x}" y="${165 - hh}" width="64" height="${hh}" rx="6" fill="var(--violet)" fill-opacity=".8" stroke="var(--line-2)" stroke-width="2"/>${txt(x + 32, 159 - hh, v + "%", { s: 12 })}${txt(x + 32, 183, ids[i], { s: 12 })}`;
    }).join("")}</svg>`;
  };
  B.add("l4-tournament", [
    { type: "pick", q: "Tournaments of size 3 are drawn WITHOUT replacement from these six individuals. Tap every individual that can never win one.", fig: bars([8, 3, 6, 9, 2, 5], { ids: ["F1", "F2", "F3", "F4", "F5", "F6"], labels: ["F1", "F2", "F3", "F4", "F5", "F6"], max: 11 }), a: ["F2", "F5"], why: "To win, an individual needs the other two entrants to be weaker. F5 (2) and F2 (3) are the two weakest, so there are never two weaker individuals to share the tournament with. F6 (5) can win if F2 and F5 are drawn with it. With replacement they could win by being drawn three times." },
    { type: "cat", q: "What happens to tournament selection pressure?", buckets: ["Raises pressure", "Lowers pressure", "No change"], items: [["Tournament size grows from 3 to 8", 0], ["Tournament size shrinks from 6 to 2", 1], ["Every fitness is multiplied by 1000", 2], ["The best individual's fitness is made 1000 times larger, others stay", 2], ["Tournament size shrinks from 2 to 1", 1], ["1000 is added to every fitness", 2]], why: "A tournament only compares who is better, so any change that keeps the order the same does nothing. Pressure moves only with the tournament size: bigger means the winner is more likely to be near the top." },
    { type: "mcq", q: "Chart A shows each rank's chance of winning a tournament of size 2 (with replacement) in a population of 5. Chart B is the same population with one setting changed. What changed?", fig: `<svg viewBox="0 0 520 380" style="max-height:380px"><g>${chartFig([36, 28, 20, 12, 4], "Chart A: size 2").replace(/^<svg[^>]*>|<\/svg>$/g, "")}</g><g transform="translate(0 190)">${chartFig([49, 30, 15, 6, 1], "Chart B").replace(/^<svg[^>]*>|<\/svg>$/g, "")}</g></svg>`, o: ["A larger tournament size", "A smaller tournament size", "Drawing the entrants without replacement", "A population twice as big"], a: 0, why: "Chart B puts more weight on the best (49% against 36%) and less on the rest, so the pressure is higher: a larger tournament. Without replacement the worst could never win (0%), and a bigger population would not stay at 5 slots." },
    { type: "bug", q: "This tournament should return the fittest of t random entrants (maximising). Tap the faulty line.", code: ["def tournament(pop, t):", "    best = None", "    for _ in range(t):", "        cand = random.choice(pop)", "        if best is None or cand.fit < best.fit:", "            best = cand", "    return best"], a: 4, why: "The comparison keeps the weaker candidate, so the function returns the worst of the entrants. It should keep cand when cand.fit > best.fit." },
    { type: "multi", q: "When is tournament selection a better fit than roulette?", o: ["Some fitness values are negative", "The population is spread over many machines, so adding up all fitness values is awkward", "You want one simple dial (t) for how greedy selection is", "You need probabilities exactly proportional to fitness", "You must sort the whole population before every selection"], a: [0, 1, 2], why: "Tournaments only compare entrants, so negative values are fine, no global total is needed, and t is the pressure dial. Exact proportionality is roulette's job, and needing a sort is a cost of rank selection, not of tournaments." },
  ]);

  /* ---------- l4-mutation ---------- */
  const permFig = (() => {
    const rows = [["M1", [3, 1, 6, 4, 2, 5]], ["M2", [3, 1, 4, 6, 2, 2]], ["M3", [3, 2, 6, 4, 1, 5]], ["M4", [3, 1, 4, 6, 2, 7]], ["M5", [4, 1, 4, 6, 2, 5]]];
    const parent = `${txt(10, 36, "Parent", { a: "start", s: 14 })}${strip([3, 1, 4, 6, 2, 5].map((n) => [n, "var(--bg-2)"]), 100, 16)}`;
    const body = rows.map(([id, g], i) => `<g data-pick="${id}"><rect x="6" y="${58 + i * 44}" width="320" height="40" rx="10" fill="var(--panel)" stroke="var(--line-2)" stroke-width="2"/>${txt(36, 84 + i * 44, id, { s: 14 })}${strip(g.map((n) => [n]), 100, 61 + i * 44, { cw: 34, ch: 34 })}</g>`).join("");
    return `<svg viewBox="0 0 340 285" style="max-height:285px;max-width:380px">${parent}${body}</svg>`;
  })();
  B.add("l4-mutation", [
    { type: "pick", q: "The parent is a tour of cities 1 to 6, each visited once. Five mutations were tried. Tap every child that is still a valid tour.", fig: permFig, a: ["M1", "M3"], why: "M1 swapped two cities and M3 reversed a segment (1 4 6 2 became 2 6 4 1); both still contain each city exactly once. M2 repeats city 2 and loses 5, M4 contains city 7, which does not exist, and M5 visits 4 twice. Those came from gene-by-gene changes that ignore the permutation." },
    { type: "match", q: "Match each before and after to the mutation that made it.", pairs: [["10110 → 10010", "Bit flip"], ["(2.40, 7.10) → (2.46, 7.03)", "Gaussian nudge"], ["A B C D E → A E C D B", "Swap two genes"], ["A B C D E → A B E D C", "Reverse a segment"], ["A B C D E → A C D B E", "Move one gene"]], why: "A bit flip changes one binary gene; Gaussian noise gives small random changes to real values; swap exchanges B and E; inversion reverses the stretch C D E; insertion moves B to just after D." },
    { type: "cat", q: "Does each operator take small steps or big jumps?", buckets: ["Small steps (exploit)", "Big jumps (explore)"], items: [["Gaussian noise with a standard deviation of 0.01", 0], ["Reset a gene to any value in its range", 1], ["Flip one bit (rate 1/L)", 0], ["Replace the whole chromosome with a random one", 1], ["Gaussian noise with a standard deviation as large as the whole range", 1], ["Swap two neighbouring cities in a tour", 0]], why: "Small changes give children that are similar to a good parent, so they have a fair chance of being good (exploitation). Large changes can reach anywhere but usually land somewhere poor (exploration). A good mutation scheme needs both: mostly small steps, with the ability to jump." },
    { type: "slider", q: "A 100-bit string is mutated with each bit flipping independently with probability 1/100. About what percentage of children are exact copies of their parent (no bit flips at all)?", min: 0, max: 100, step: 5, ans: 37, tol: 10, unit: "%", hint: "Each bit survives with probability 0.99. For 100 bits this is the classic (1 − 1/n)^n, which is about 1/e ≈ 0.37.", why: "With one flip expected per child, a surprising number of children get none: (1 − 1/100)^100 ≈ 0.37, so over a third are copies. That is worth knowing when you wonder why progress sometimes stalls: those children cost an evaluation and add nothing." },
    { type: "bug", q: "A mutation should return a changed COPY and leave the parent alone. Tap the faulty line.", code: ["def mutate(parent, sigma):", "    child = parent", "    i = random.randrange(len(child))", "    child[i] += random.gauss(0, sigma)", "    return child"], a: 1, why: "child = parent does not copy a Python list, it just gives it a second name. The parent in the population is changed as well, even when the child is later rejected. It needs child = parent[:] or list(parent)." },
  ]);

  /* ---------- l4-crossover ---------- */
  const cutFig = (() => {
    const src = ["B", "B", "O", "O", "O", "B", "B", "B"], x0 = 60, cw = 50;
    const colour = { B: "var(--blue-dim, var(--blue))", O: "var(--amber)" };
    const cells = src.map((s, i) => `<rect x="${x0 + i * cw}" y="30" width="${cw - 4}" height="${cw - 4}" rx="8" fill="${s === "B" ? "var(--blue)" : "var(--amber)"}" fill-opacity=".8" stroke="var(--line-2)" stroke-width="2"/>${txt(x0 + i * cw + (cw - 4) / 2, 59, i + 1, { s: 14, c: "#fff" })}`).join("");
    const gaps = Array.from({ length: 7 }, (_, i) => `<g data-pick="g${i + 1}"><rect x="${x0 + (i + 1) * cw - 14}" y="82" width="22" height="40" rx="6" fill="var(--panel)" stroke="var(--line-2)" stroke-width="2"/>${txt(x0 + (i + 1) * cw - 3, 144, "g" + (i + 1), { s: 14, c: "var(--text-dim)" })}</g>`).join("");
    return `<svg viewBox="0 0 480 155" style="max-height:155px">${txt(240, 18, "Blue: from parent 1. Orange: from parent 2", { s: 15 })}${cells}${gaps}</svg>`;
  })();
  const maskFig = `<svg viewBox="0 0 440 150" style="max-height:150px">${txt(8, 30, "Parent 1", { a: "start" })}${strip("ABCDEFGH".split("").map((c) => [c, "var(--blue)", "#fff"]), 90, 12, { cw: 40 })}${txt(8, 78, "Parent 2", { a: "start" })}${strip("abcdefgh".split("").map((c) => [c, "var(--amber)", "#fff"]), 90, 60, { cw: 40 })}${txt(8, 128, "Child", { a: "start" })}${strip("ABcdEfGH".split("").map((c) => [c]), 90, 110, { cw: 40 })}</svg>`;
  B.add("l4-crossover", [
    { type: "pick", q: "A k-point crossover made this child. Tap every cut point (gap between genes) that was used.", fig: cutFig, a: ["g2", "g5"], why: "The source changes from blue to orange between genes 2 and 3 and back to blue between genes 5 and 6. Those are the two cuts, so this was 2-point crossover. Where neighbouring genes share a colour there is no cut." },
    { type: "mcq", q: "The child below was made by uniform crossover from the two parents. Which mask (1 = take the gene from parent 2) produced it?", fig: maskFig, o: ["00110100", "11001011", "00110010", "00101100"], a: 0, why: "Compare gene by gene: A, B from parent 1 (0, 0), c, d from parent 2 (1, 1), E from parent 1 (0), f from parent 2 (1), G, H from parent 1 (0, 0). That is 00110100. The mask 11001011 is its opposite and would build the other child." },
    { type: "cat", q: "Parents are AAAAAA and BBBBBB. Which crossover can produce each child?", buckets: ["1-point", "2-point but not 1-point", "Uniform only", "No crossover"], items: [["AAABBB", 0], ["BBBBAA", 0], ["AABBAA", 1], ["BAAAAB", 1], ["ABABAB", 2], ["AACBBB", 3]], why: "One cut gives a block of A next to a block of B. Two cuts give a swapped middle. ABABAB alternates too often for two cuts, so it needs a mask. AACBBB contains a C that neither parent has, and crossover only recombines existing genes. New values come from mutation." },
    { type: "multi", q: "Which of these situations make crossover produce only exact copies of the parents?", o: ["Both parents are identical", "The uniform mask is all 1s (child 1 copies parent 2)", "A 1-point cut falls between genes 4 and 5 of 8", "The crossover probability test fails and no crossover is applied", "The parents differ at every gene"], a: [0, 1, 3], why: "Identical parents leave nothing to recombine, an all-1 mask hands over everything from one parent, and skipping crossover just copies them. A cut in the middle and parents that differ everywhere both give genuinely new children." },
    { type: "bug", q: "This should build two children by swapping each gene with probability 0.5 (c1 starts as a copy of p1, c2 as a copy of p2). Tap the faulty line.", code: ["c1, c2 = p1[:], p2[:]", "for i in range(L):", "    if random() < 0.5:", "        c1[i] = p1[i]", "        c2[i] = p1[i]"], a: 3, why: "Swapping means child 1 takes parent 2's gene here, but c1[i] = p1[i] writes the value it already holds. Child 1 would always stay a copy of parent 1. It should be c1[i] = p2[i]." },
  ]);

  /* ---------- l4-lab ---------- */
  const labFig = (() => {
    const w = 520, h = 220, X = (g) => 40 + (g / 30) * 460, Y = (v) => 180 - v * 150;
    const line = (f, c) => `<path d="${Array.from({ length: 31 }, (_, g) => `${g ? "L" : "M"}${X(g).toFixed(1)} ${Y(f(g)).toFixed(1)}`).join(" ")}" fill="none" stroke="${c}" stroke-width="3"/>`;
    const best = (g) => g < 10 ? 0.5 + 0.04 * g : 0.9;
    const mean = (g) => g < 12 ? 0.45 + 0.0375 * g : 0.9;
    const div = (g) => Math.max(0, 0.8 - 0.8 * g / 12);
    const ticks = [4, 8, 12, 20, 28].map((g) => `<g data-pick="g${g}"><circle cx="${X(g)}" cy="198" r="13" fill="var(--panel)" stroke="var(--line-2)" stroke-width="3"/>${txt(X(g), 202, g, { s: 11 })}</g>`).join("");
    return `<svg viewBox="0 0 ${w} ${h}" style="max-height:${h}px"><line x1="40" x2="500" y1="180" y2="180" stroke="var(--line-2)" stroke-width="2"/>${line(div, "var(--rose)")}${line(mean, "var(--blue)")}${line(best, "var(--teal)")}${ticks}${txt(46, 14, "best", { a: "start", c: "var(--teal-ink)" })}${txt(92, 14, "mean", { a: "start", c: "var(--blue-ink)" })}${txt(144, 14, "diversity", { a: "start", c: "var(--rose-ink)" })}</svg>`;
  })();
  const gridFig = (() => {
    const bad = [[1, 2], [4, 9], [7, 4], [10, 7]], c = 26, x0 = 20, y0 = 10;
    let s = "";
    for (let r = 0; r < 12; r++) for (let k = 0; k < 12; k++) {
      const on = (r * 7 + k * 3 + (r * k)) % 5 < 2, wrong = bad.some(([a, b]) => a === r && b === k);
      s += `<rect x="${x0 + k * c}" y="${y0 + r * c}" width="${c - 2}" height="${c - 2}" rx="3" fill="${on ? "var(--ink)" : "var(--bg-2)"}" stroke="${wrong ? "var(--rose)" : "var(--line)"}" stroke-width="${wrong ? 4 : 1}"/>`;
    }
    return `<svg viewBox="0 0 352 ${y0 + 12 * c + 6}" style="max-height:330px;max-width:380px">${s}</svg>`;
  })();
  B.add("l4-lab", [
    { type: "pick", q: "The dashboard of one lab run is below (generations on the x axis). Tap the first mark at which the run is already stuck for good.", fig: labFig, a: "g12", why: "Diversity hits 0 at generation 12 and the mean has caught up with the best, so every member is the same. With no mutation left to create anything new, nothing can improve after that. At generation 8 diversity is still above 0 and the mean is still climbing." },
    { type: "mcq", q: "All three runs spent exactly 2,000 fitness evaluations on the same picture. Why does run C trail?", fig: `<table class="t"><tr><th>Run</th><th>Population</th><th>Scheme</th><th class="num">Final best</th></tr><tr><td>A</td><td>10</td><td>steady-state, 1 child per step</td><td class="num">0.88</td></tr><tr><td>B</td><td>100</td><td>steady-state, 1 child per step</td><td class="num">0.80</td></tr><tr><td>C</td><td>100</td><td>generational, 100 children per generation</td><td class="num">0.71</td></tr></table>`, o: ["It got only 20 generations, as each one costs 100 evaluations", "Big populations can never beat small ones in a fixed budget", "Generational schemes are not able to use any mutation at all", "2,000 evaluations is too few for a population of any size"], a: 0, why: "The budget is shared out differently: run C gets 2000 ÷ 100 = 20 generations of improvement, run B gets 2000 steps and run A gets 2000 steps on a small population. When the budget is fixed, a bigger population means fewer rounds of selection. That is the cost of more diversity." },
    { type: "order", q: "Put the typical story of a lab run in order.", items: ["The population starts as random noise, with about half the pixels right", "The best rises fast as good pixels spread through the population", "Progress slows because most pixels are already right", "Only rare lucky mutations fix the last few wrong pixels"], why: "Random pictures match about half the pixels, so early improvements are cheap and spread quickly. As the picture fills in, fewer changes help, and the last fixes need a lucky mutation to hit exactly the right pixel." },
    { type: "slider", q: "This best candidate has 4 wrong pixels (red outlines) out of 144. A mutation flips exactly one random pixel. About what percentage of such mutants are better than the parent?", fig: gridFig, min: 0, max: 20, step: 1, ans: 3, tol: 2, unit: "%", hint: "A flip helps only if it hits one of the 4 wrong pixels: 4 out of 144, about 1 in 36.", why: "Only the 4 wrong pixels can be improved, so 4/144 ≈ 3% of single flips help. The other 97% make it worse. That is why late progress is slow: the closer you get, the harder improvements are to find." },
    { type: "bug", q: "This fitness function should give 1.0 for a perfect copy of the target. Tap the faulty line.", code: ["def fitness(pic, target):", "    wrong = sum(1 for a, b in zip(pic, target) if a != b)", "    return wrong / len(target)"], a: 2, why: "wrong / len(target) is the error rate: 0 for a perfect copy and larger for worse pictures, so the GA would be steered towards the worst pictures. Fitness should be 1 - wrong / len(target)." },
  ]);
})();
