/* NIC revision bank, second set of visual and varied questions, part 3.
   Lecture 4 (selection, replacement, pressure, mutation, crossover, the lab). Every figure is needed to answer. */
(function () {
  const B = NIC.bank;
  const FONT = "font:800 13px var(--sans)";
  const txt = (x, y, s, o = {}) => `<text x="${x}" y="${y}" text-anchor="${o.a || "middle"}" style="font:${o.w || 800} ${o.s || 13}px var(--sans);fill:${o.c || "var(--text)"}">${s}</text>`;

  /* Bar chart. vals: numbers; ids: data-pick ids (optional); labels under bars; line: {y, label} horizontal marker. */
  function bars(vals, { ids = null, labels = null, max = null, w = 520, h = 210, line = null, colors = null, show = true, inside = false, fmt = (v) => v } = {}) {
    const m = max || Math.max(...vals) * 1.1, n = vals.length, bw = Math.min(54, (w - 40) / n - 12), gap = (w - 40) / n;
    const Y = (v) => h - 34 - (v / m) * (h - 66);
    const body = vals.map((v, i) => {
      const x = 20 + gap * i + (gap - bw) / 2;
      const r = `<rect x="${x}" y="${Y(v)}" width="${bw}" height="${h - 34 - Y(v)}" rx="6" fill="${colors ? colors[i] : "var(--blue)"}" stroke="var(--line-2)" stroke-width="2" fill-opacity=".85"/>`;
      const val = show ? (inside ? txt(x + bw / 2, h - 44, fmt(v), { s: 12, c: "#fff" }) : txt(x + bw / 2, Y(v) - 6, fmt(v), { s: 12 })) : "";
      const lab = labels ? txt(x + bw / 2, h - 14, labels[i]) : "";
      return ids ? `<g data-pick="${ids[i]}">${r}${val}${lab}</g>` : `<g>${r}${val}${lab}</g>`;
    }).join("");
    const ln = line ? `<line x1="14" x2="${w - 10}" y1="${Y(line.y)}" y2="${Y(line.y)}" stroke="var(--rose)" stroke-width="3" stroke-dasharray="7 5"/>${txt(w - 12, Y(line.y) - 6, line.label, { a: "end", c: "var(--rose-ink)" })}` : "";
    return `<svg viewBox="0 0 ${w} ${h}" style="max-height:${h}px"><line x1="14" x2="${w - 10}" y1="${h - 34}" y2="${h - 34}" stroke="var(--line-2)" stroke-width="2"/>${body}${ln}</svg>`;
  }

  /* A row of genes. cells: [text, colour]. */
  function strip(cells, x, y, { cw = 34, ch = 34 } = {}) {
    return cells.map((c, i) => `<rect x="${x + i * cw}" y="${y}" width="${cw - 3}" height="${ch}" rx="6" fill="${c[1] || "var(--panel)"}" stroke="var(--line-2)" stroke-width="2"/>${txt(x + i * cw + (cw - 3) / 2, y + ch / 2 + 5, c[0], { c: c[2] || "var(--text)" })}`).join("");
  }

  /* Pie wheel. vals, labels; ids optional (pick). */
  function pie(vals, labels, cx, cy, r, ids, cols) {
    const tot = vals.reduce((a, b) => a + b, 0); let a0 = -Math.PI / 2;
    return vals.map((v, i) => {
      const a1 = a0 + (v / tot) * Math.PI * 2, big = a1 - a0 > Math.PI ? 1 : 0;
      const p = `M${cx} ${cy} L${(cx + r * Math.cos(a0)).toFixed(1)} ${(cy + r * Math.sin(a0)).toFixed(1)} A${r} ${r} 0 ${big} 1 ${(cx + r * Math.cos(a1)).toFixed(1)} ${(cy + r * Math.sin(a1)).toFixed(1)} Z`;
      const mid = (a0 + a1) / 2, lx = cx + r * 0.66 * Math.cos(mid), ly = cy + r * 0.66 * Math.sin(mid);
      a0 = a1;
      const g = `<path d="${p}" fill="${cols[i]}" fill-opacity=".75" stroke="var(--panel)" stroke-width="3"/>${txt(lx, ly + 5, labels[i], { s: 13 })}`;
      return ids ? `<g data-pick="${ids[i]}">${g}</g>` : `<g>${g}</g>`;
    }).join("");
  }

  
  const addSvg = (svg, extra) => svg.replace(/<\/svg>$/, extra + "</svg>");
  const tbl = (head, rows, pick) => `<table class="t"><tr>${head.map((h, i) => `<th${i ? ' class="num"' : ""}>${h}</th>`).join("")}</tr>${rows.map((r, k) => `<tr${pick ? ` data-pick="${pick[k]}"` : ""}>${r.map((c, i) => `<${i ? 'td class="num"' : "td"}>${c}</${i ? "td" : "td"}>`).join("")}</tr>`).join("")}</table>`;

  /* ---------- l4-types ---------- */
  B.add("l4-types", [
    { type: "pick", q: "A generational GA keeps 2 elites. Here is the current population (fitness, higher is better). Tap every member that is certain to be in the next generation.", fig: bars([0.42, 0.9, 0.55, 0.8, 0.3, 0.65, 0.7, 0.5], { ids: ["m1", "m2", "m3", "m4", "m5", "m6", "m7", "m8"], labels: ["M1", "M2", "M3", "M4", "M5", "M6", "M7", "M8"], max: 1.05, fmt: (v) => v.toFixed(2) }), a: ["m2", "m4"], why: "Elitism copies the best 2 members unchanged: 0.90 (M2) and 0.80 (M4). Everyone else, even a decent 0.70, has to be picked as a parent and survive crossover and mutation to leave any trace, and the new population has no room for the old members." },
    { type: "bug", q: "A generational GA with 2 elites should end each generation with a population of the same size. Tap the faulty line.", code: ["pop.sort(key=fitness, reverse=True)", "new = pop[:2]", "while len(new) < len(pop):", "    new.append(make_child(pop))", "pop = pop + new"], a: 4, why: "pop + new glues the old population and the new one together, so the population doubles every generation and nothing is ever replaced. It should be pop = new. The elites are already inside new." },
    { type: "match", q: "Match each design choice to its main consequence.", pairs: [["Generational", "Children wait a whole generation before they can breed"], ["Steady-state", "A new child can be picked as a parent straight away"], ["No elitism", "The best fitness can fall from one generation to the next"], ["Elitism of 2", "The two best survive untouched into the next generation"]], why: "Generational schemes build a full new population from the old one, so children cannot be parents until the next round. Steady-state inserts one child at a time into the live population. Elitism is what protects the best; without it, a bad round of crossover and mutation can lose it." },
    { type: "slider", q: "A steady-state GA has a population of 100 and makes one child per step, replacing one member each time. After 50 steps, at most what percentage of the population can be new children?", min: 0, max: 100, step: 5, ans: 50, tol: 5, unit: "%", hint: "Each step replaces at most 1 member out of 100. 50 steps replace at most 50 members, which is half.", why: "One replacement per step means 50 steps touch at most 50 of the 100 slots. It is 'at most' because a slot can be overwritten twice, and a child may be rejected. This slow, gentle turnover is why steady-state GAs change the population smoothly rather than in big jumps." },
    { type: "multi", q: "A generational GA has a population of 20 and 2 elites. Which statements are true?", o: ["18 new children are made and evaluated each generation", "The elites can still be picked as parents for the children", "The best fitness in the population can never fall", "The elites skip the breeding stage entirely, so they are never parents", "With 20 elites the GA would stand still, because no children are made"], a: [0, 1, 2, 4], why: "Elites are copied into the new population (2 slots), leaving 18 slots for children. They still sit in the old population, so selection can pick them as parents. Because the best is copied, best fitness cannot fall. Setting elites equal to the population size leaves no room for children, so nothing ever changes." },
  ]);

  /* ---------- l4-replacement ---------- */
  B.add("l4-replacement", [
    { type: "pick", q: "Replace-first-weaker, scanning right from slot 3 and wrapping round. The child has fitness 0.65 (dashed line). Tap the slot that gets overwritten.", fig: addSvg(bars([0.8, 0.4, 0.9, 0.7, 0.6, 0.5], { ids: ["s1", "s2", "s3", "s4", "s5", "s6"], labels: ["Slot 1", "Slot 2", "Slot 3", "Slot 4", "Slot 5", "Slot 6"], max: 1.15, line: { y: 0.65, label: "child 0.65" }, fmt: (v) => v.toFixed(2) }), txt(220, 20, "scan starts here ▼", { s: 12, c: "var(--amber-ink)" })), a: "s5", why: "Slot 3 (0.90) and slot 4 (0.70) are both stronger than the child, so the scan carries on. Slot 5 (0.60) is the first one weaker than 0.65, so it is overwritten and the scan stops. Slot 6 (0.50) is weaker still and would be the victim under replace-weakest, but this strategy never gets that far." },
    { type: "mcq", q: "Two runs each used one replacement rule on the same problem. Which statement fits the evidence best?", fig: tbl(["Run", "After 3,000 steps", "Mean fitness", "Distinct genomes of 50"], [["P", "best 0.94", "0.93", "3"], ["Q", "best 0.86", "0.71", "28"]]), o: ["P is replace-weakest: it keeps culling the lowest, so the mean climbs and variety drains", "Q is replace-weakest: it shields weak members, so many different genomes stay alive", "P is replace-first-weaker: random victims keep the mean high but variety low", "Neither can be told apart, because replacement rules never change variety"], a: 0, why: "Replace-weakest always removes the lowest member, which is strong selection pressure: the mean rises right up to the best and the population fills with near-copies (3 genomes). Replace-first-weaker picks a victim by scan position, so weaker members linger: lower mean, more variety (28), and a slower best." },
    { type: "multi", q: "Which statements about the two replacement rules are true?", o: ["Replace-first-weaker can overwrite the current best, if the child is better still", "Replace-weakest can never overwrite the current best (population of 2 or more)", "Under replace-first-weaker the best fitness in the population still never falls", "Replace-weakest picks its victim at random, so it needs no comparisons", "Replace-first-weaker can insert a child that is weaker than every member"], a: [0, 1, 2], why: "If the child beats the best, the best is 'weaker than the child' and may be the first the scan meets, but the child is better still, so best fitness only goes up. Replace-weakest removes the lowest, never the best. It needs a full pass to find the weakest, not a random pick. And a child weaker than everyone has no weaker member to replace, so it is rejected." },
    { type: "slider", q: "A population of 1,000 uses replace-weakest, which looks at every member to find the weakest. About how many members are looked at in total over 5,000 steps?", min: 0, max: 10, step: 1, ans: 5, tol: 1, unit: " million", hint: "1,000 looks per step × 5,000 steps = 5,000,000.", why: "1,000 × 5,000 = 5 million. That is the price of strong pressure: replace-first-weaker usually stops after a couple of looks, so on big populations it is far cheaper per step (a heap or a tracked 'weakest' pointer can reduce the cost, but the plain scan is linear)." },
    { type: "bug", q: "Replace-first-weaker should scan the slots and overwrite the first member weaker than the child, then stop. Tap the faulty line.", code: ["for i in range(P):", "    if fit[i] < child_fit:", "        pop[i] = child", "        fit[i] = child_fit", "    break"], a: 4, why: "The break is indented under the for loop, not under the if, so the loop always stops after slot 1 whether or not it was replaced. Most children would never be inserted. The break belongs inside the if, after the two assignments." },
  ]);

  /* ---------- l4-pressure ---------- */
  const takeFig = (() => {
    const w = 520, h = 230, X = (g) => 50 + g * 60, Y = (p) => 190 - p * 150;
    const curves = [["A", [0.02, 0.078, 0.276, 0.726, 0.994, 1, 1, 1], "var(--teal)"], ["B", [0.02, 0.149, 0.726, 1, 1, 1, 1, 1], "var(--blue)"], ["C", [0.02, 0.04, 0.078, 0.149, 0.276, 0.476, 0.726, 0.925], "var(--amber)"]];
    const paths = curves.map(([id, v, c]) => { const d = v.map((p, g) => `${g ? "L" : "M"}${X(g)} ${Y(p)}`).join(" "); return `<g data-pick="${id}"><path d="${d}" fill="none" stroke="transparent" stroke-width="22" stroke-linecap="round"/><path d="${d}" fill="none" stroke="${c}" stroke-width="4" stroke-linecap="round"/></g>`; }).join("");
    const leg = curves.map(([id, , c], i) => `<circle cx="${300 + i * 70}" cy="14" r="7" fill="${c}"/>${txt(312 + i * 70, 19, id, { a: "start" })}`).join("");
    const ticks = [0, 1, 2, 3, 4, 5, 6, 7].map((g) => txt(X(g), 212, g, { s: 11, c: "var(--text-dim)" })).join("");
    return `<svg viewBox="0 0 ${w} ${h}" style="max-height:${h}px"><line x1="40" x2="${w - 20}" y1="190" y2="190" stroke="var(--line-2)" stroke-width="2"/>${txt(10, 14, "Share of population that copies the best", { a: "start", c: "var(--text-dim)", s: 12 })}${leg}${paths}${ticks}${txt(490, 226, "generation", { a: "end", s: 11, c: "var(--text-faint)" })}${txt(36, 44, "100%", { a: "end", s: 11, c: "var(--text-dim)" })}</svg>`;
  })();
  B.add("l4-pressure", [
    { type: "pick", q: "Three runs start with 2% of the population as copies of the best individual (no mutation, no crossover). They use tournament sizes 2, 4 and 8. Tap the curve of the size 8 run.", fig: takeFig, a: "B", why: "A bigger tournament means each pick is more likely to include a good entrant, so copies of the best spread faster. Size 8 takes over in about 3 generations (B), size 4 needs about 5 (A) and size 2 is still not complete after 7 (C). Fast takeover is exactly what high selection pressure means." },
    { type: "order", q: "Put these selection rules from the LOWEST to the HIGHEST selection pressure.", items: ["Random selection (tournament of 1)", "Binary tournament (size 2)", "Tournament of size 5", "Always pick the single best member"], why: "Size 1 ignores fitness altogether. Each extra entrant raises the chance that a strong individual is in the draw. Always taking the best is the extreme end: the rest of the population never breeds at all." },
    { type: "match", q: "Match each symptom to the most sensible fix.", pairs: [["Everyone is a copy of one genome by generation 15", "Lower the tournament size or raise the mutation rate"], ["Best and mean both crawl, with plenty of variety left", "Raise the tournament size"], ["The roulette wheel is almost flat late in the run", "Switch to rank selection"], ["Best fitness dips between generations", "Add elitism"]], why: "Too much pressure kills variety, so soften it. Too little pressure wastes variety, so tighten it. Roulette flattens as fitnesses converge, and rank selection keeps its spread. A dipping best is a loss of the champion, and elitism copies it forward." },
    { type: "bug", q: "A self-adjusting EA should loosen selection when the population has almost converged. Tap the faulty line.", code: ["div = len(set(pop)) / len(pop)", "if div < 0.1:          # almost everyone identical", "    t = t + 1", "return tournament(pop, t)"], a: 2, why: "When diversity is below 10%, selection is already too strong, and a bigger t makes it stronger. It should reduce t (for example t = max(2, t - 1)). The comparison is right; the direction of the change is wrong." },
    { type: "slider", q: "Entrants for a size 3 tournament are drawn with replacement from a large population. About what percentage of the time does the winner come from the better half?", min: 50, max: 100, step: 5, ans: 87.5, tol: 5, unit: "%", hint: "The winner is from the worse half only if all 3 entrants are. (1/2) × (1/2) × (1/2) = 1/8.", why: "All three entrants must be from the worse half for the winner to be from it: 1/8 = 12.5%. So the better half supplies 87.5% of winners. Even a modest tournament size is a strong filter." },
  ]);

  /* ---------- l4-roulette ---------- */
  const stripFig = (() => {
    const x0 = 40, u = 44, segs = [["A", 3, "var(--teal)"], ["B", 1, "var(--blue)"], ["C", 4, "var(--amber)"], ["D", 2, "var(--violet)"]];
    let c = 0;
    const body = segs.map(([id, v, col]) => { const x = x0 + c * u, s = `<g data-pick="${id}"><rect x="${x}" y="50" width="${v * u}" height="56" fill="${col}" fill-opacity=".8" stroke="var(--line-2)" stroke-width="2"/>${txt(x + (v * u) / 2, 84, id + " " + v, { s: 14, c: "#fff" })}</g>`; c += v; return s; }).join("");
    const ticks = [0, 3, 4, 8, 10].map((t) => txt(x0 + t * u, 128, t, { s: 12, c: "var(--text-dim)" })).join("");
    const mx = x0 + 3.4 * u;
    return `<svg viewBox="0 0 520 150" style="max-height:150px">${txt(x0, 16, "The wheel laid flat: slice size = fitness", { a: "start", c: "var(--text-dim)", s: 12 })}${body}${ticks}<path d="M${mx} 46 l-7 -12 h14 z" fill="var(--rose)"/>${txt(mx, 30, "random point 3.4", { a: "start", c: "var(--rose-ink)", s: 12 }).replace(`x="${mx}"`, `x="${mx + 12}"`)}</svg>`;
  })();
  const wheelsFig = (() => {
    const cols = ["var(--teal)", "var(--blue)", "var(--amber)", "var(--violet)"];
    const lab = (a) => a.map((v, i) => "F" + (i + 1) + " " + v);
    return `<svg viewBox="0 0 520 250" style="max-height:250px">${txt(130, 18, "Generation 2", { s: 15 })}<g data-pick="early">${pie([1, 2, 5, 8], lab([1, 2, 5, 8]), 130, 135, 95, null, cols)}</g>${txt(390, 18, "Generation 80", { s: 15 })}<g data-pick="late">${pie([91, 92, 95, 98], lab([91, 92, 95, 98]), 390, 135, 95, null, cols)}</g></svg>`;
  })();
  B.add("l4-roulette", [
    { type: "pick", q: "Individuals A to D sit on the wheel in that order, laid out flat below (slice size = fitness). The random point lands at 3.4. Tap the individual that is selected.", fig: stripFig, a: "B", why: "The running totals are A 0 to 3, B 3 to 4, C 4 to 8 and D 8 to 10. The point 3.4 sits in the narrow B slice, even though B has the smallest fitness. A small slice is picked rarely (1 in 10 spins), not never." },
    { type: "pick", q: "The same roulette selection is used throughout one run. Tap the wheel where selection pressure has all but vanished.", fig: wheelsFig, a: "late", why: "In generation 80 every slice is about a quarter, so each individual is picked about equally often: selection is nearly random. In generation 2 the best owns about half the wheel. As a population converges, fitness ratios shrink towards 1, which is why roulette stalls late in a run and rank selection helps." },
    { type: "match", q: "Match each change to what it does to roulette selection probabilities.", pairs: [["Multiply every fitness by 10", "Nothing changes"], ["Add 100 to every fitness", "The wheel gets flatter"], ["Square every fitness (all positive)", "The best gets a bigger share"], ["Use 1 divided by tour length for a TSP", "Shorter tours get bigger slices"]], why: "Probabilities are shares of the total, so scaling cancels out. Adding a constant pushes every share towards equal. Squaring exaggerates differences (3 versus 2 becomes 9 versus 4). For minimisation you need a transform that rewards small values, such as 1 divided by the length." },
    { type: "bug", q: "This builds the running totals (the wheel edges) for roulette selection. Tap the faulty line.", code: ["cum = []", "running = 0", "for ind in pop:", "    running = ind.fit", "    cum.append(running)"], a: 3, why: "running = ind.fit overwrites the total each time, so cum just repeats the fitnesses and is not increasing. It must add: running += ind.fit. Only then do the entries mark the right edges of the slices." },
    { type: "mcq", q: "In 1,000 roulette spins on four individuals A, B, C, D the picks were as shown. Which fitness values for A, B, C, D could have produced them?", fig: bars([405, 297, 208, 90], { labels: ["A", "B", "C", "D"], max: 480, h: 200 }), o: ["4, 3, 2, 1", "10, 5, 3, 2", "4, 4, 1, 1", "1, 2, 3, 4"], a: 0, hint: "Shares of about 40, 30, 20 and 10 per cent are in the ratio 4 : 3 : 2 : 1.", why: "The picks are about 41%, 30%, 21% and 9%, the ratio 4 : 3 : 2 : 1. Fitnesses 10, 5, 3, 2 would give A half the picks, 4, 4, 1, 1 would make A and B equal, and 1, 2, 3, 4 would put D on top." },
  ]);

  /* ---------- l4-rank ---------- */
  B.add("l4-rank", [
    { type: "slider", q: "Linear rank selection on 10 individuals (ranks 1 to 10). About what percentage chance does the best individual have of being picked each time?", min: 0, max: 40, step: 2, ans: 18, tol: 4, unit: "%", hint: "Ranks 1 to 10 add up to 55, which is about 50. So 10 out of about 55 is roughly 1 in 5.", why: "The best has rank 10 out of a total of 1 + 2 + … + 10 = 55, so 10/55 ≈ 18%. This holds whether the best fitness is 11 or 11 million: rank selection only looks at the order." },
    { type: "pick", q: "Five individuals with fitness 50, 49, 48, 10 and 1. The selection method is switched from roulette to linear rank. Tap every individual whose chance of being picked goes DOWN.", fig: bars([50, 49, 48, 10, 1], { ids: ["A", "B", "C", "D", "E"], labels: ["A", "B", "C", "D", "E"], max: 58 }), a: ["B", "C"], hint: "Roulette shares are fitness ÷ 158, about 32, 31, 30, 6 and 1 per cent. Rank shares are 5, 4, 3, 2 and 1 out of 15: about 33, 27, 20, 13 and 7 per cent.", why: "Roulette gives A, B and C about 32%, 31% and 30%, and D and E 6% and 0.6%. Linear rank gives 33%, 27%, 20%, 13% and 7%. B and C lose share because the near-identical top fitnesses are spread out, D and E gain, and A nudges up from 31.6% to 33.3%." },
    { type: "multi", q: "In which populations would swapping roulette for linear rank selection change the selection probabilities a lot?", o: ["One individual is 1,000 times fitter than all the others", "Fitnesses are 10, 20, 30 and 40", "Fitnesses are 90, 91, 92 and 93", "Every fitness is multiplied by 5", "Fitnesses are 2, 4, 6 and 8"], a: [0, 2], why: "A huge outlier takes nearly the whole roulette wheel but only its rank slice under rank selection. Near-identical fitnesses give an almost flat wheel, while ranks still spread 10%, 20%, 30% and 40%. For 10, 20, 30, 40 (and 2, 4, 6, 8) the fitness shares happen to be 10%, 20%, 30%, 40%, the same as the rank shares, and multiplying by 5 changes neither." },
    { type: "bug", q: "Rank-based selection with an exponent b should turn the weights into probabilities. Tap the faulty line.", code: ["ranks = list(range(1, P + 1))", "weights = [r ** b for r in ranks]", "total = sum(ranks)", "probs = [w / total for w in weights]"], a: 2, why: "The probabilities must be divided by the sum of the weights, not the sum of the plain ranks. With b = 2 and 3 individuals the weights are 1, 4, 9 (total 14), but the code divides by 6, giving probabilities that add up to more than 1. It should be total = sum(weights)." },
  ]);

  /* ---------- l4-tournament ---------- */
  B.add("l4-tournament", [
    { type: "slider", q: "Tournaments of size 4 draw their entrants with replacement from a huge population. About what percentage of winners come from the worse half?", min: 0, max: 50, step: 1, ans: 6, tol: 2, unit: "%", hint: "All 4 entrants must be from the worse half: (1/2) × (1/2) × (1/2) × (1/2) = 1/16.", why: "The winner is from the worse half only if every entrant is, which is 1/16 ≈ 6%. With size 2 it would be 1/4 = 25%, and with size 1 it would be 50% (no selection at all)." },
    { type: "pick", q: "Tournaments of size 3, with replacement, pick the highest fitness. Here is a log of five of them. Tap the one tournament that cannot be right.", fig: tbl(["#", "Entrants", "Winner"], [["1", "4, 9, 6", "9"], ["2", "7, 7, 2", "7"], ["3", "5, 8, 3", "5"], ["4", "6, 2, 6", "6"], ["5", "1, 3, 9", "9"]], ["t1", "t2", "t3", "t4", "t5"]), a: "t3", why: "In tournament 3 the entrant with fitness 8 beats the 5, so 5 cannot be the winner. The repeated entrants in tournaments 2 and 4 are fine, because drawing with replacement lets the same individual enter twice." },
    { type: "match", q: "Match each tournament setting to its effect.", pairs: [["t = 1", "Same as picking at random"], ["t = 2", "Gentle pressure; weak individuals still win sometimes"], ["t = 20 in a population of 25", "The best wins almost every time"], ["t = 3, but the fitnesses are all doubled", "No change at all"]], why: "One entrant means no contest. Two entrants favour the better one but leave plenty of chances for the weaker. A tournament that includes most of the population nearly always contains the best. Tournaments compare fitnesses, so doubling them (any order-preserving change) changes nothing." },
    { type: "mcq", q: "500 tournaments were run on five ranked individuals, entrants drawn with replacement. The wins by rank are shown. Which tournament size was used?", fig: bars([244, 148, 76, 28, 4], { labels: ["Best", "2nd", "3rd", "4th", "Worst"], max: 290, h: 200 }), o: ["1", "2", "3", "6"], a: 2, hint: "With size t, the best wins unless all entrants avoid it: 1 − (4/5)^t. At t = 3, (4/5)^3 ≈ 0.51.", why: "The best wins 244 of 500, about 49%. For t = 3 the chance is 1 − 0.8³ ≈ 49%. Size 1 would give about 100 wins to everyone, size 2 would give the best about 36%, and size 6 would give the best about 74%." },
    { type: "multi", q: "Which statements about tournament selection are true?", o: ["Selecting a parent needs the fitness of only the entrants, not the whole population", "With replacement, a size 2 tournament can contain the same individual twice", "Doubling every fitness can change who wins", "For minimisation, picking the lowest cost in the tournament works unchanged", "The worst individual can never win"], a: [0, 1, 3], why: "Only the entrants are compared, which is why tournaments suit huge or distributed populations. Drawing with replacement allows duplicates. Only the order matters, so doubling does nothing. Minimising just flips which entrant is kept. And the worst can win if it is drawn alone (for example both entrants of a binary tournament), a chance of 1/N² for a population of N." },
  ]);

  /* ---------- l4-mutation ---------- */
  const gaussFig = (() => {
    const x0 = 40, u = 44, base = 150, hh = 100;
    const curve = (s, c, id) => { const pts = []; for (let x = 0; x <= 10; x += 0.25) pts.push(`${(x0 + x * u).toFixed(1)} ${(base - hh * Math.exp(-((x - 5) ** 2) / (2 * s * s))).toFixed(1)}`); const d = "M" + pts.join(" L"); return `<g data-pick="${id}"><path d="${d}" fill="none" stroke="transparent" stroke-width="20" stroke-linejoin="round"/><path d="${d}" fill="none" stroke="${c}" stroke-width="4" stroke-linejoin="round"/></g>`; };
    const ticks = [0, 5, 9, 10].map((t) => txt(x0 + t * u, base + 18, t, { s: 12, c: "var(--text-dim)" })).join("");
    const cols = ["var(--teal)", "var(--blue)", "var(--amber)"], names = ["A", "B", "C"];
    const leg = [["σ = 0.3", 0], ["σ = 1.5", 1], ["σ = 4", 2]];
    return `<svg viewBox="0 0 520 200" style="max-height:200px"><line x1="30" x2="490" y1="${base}" y2="${base}" stroke="var(--line-2)" stroke-width="2"/>${curve(4, cols[2], "C")}${curve(1.5, cols[1], "B")}${curve(0.3, cols[0], "A")}${ticks}<line x1="${x0 + 9 * u}" x2="${x0 + 9 * u}" y1="40" y2="${base}" stroke="var(--rose)" stroke-width="3" stroke-dasharray="6 4"/>${txt(x0 + 9 * u, 34, "better peak", { s: 12, c: "var(--rose-ink)" })}${txt(x0 + 5 * u, 34, "parent", { s: 12, c: "var(--text-dim)" })}${leg.map(([l, i]) => `<circle cx="${40 + i * 110}" cy="188" r="6" fill="${cols[i]}"/>${txt(52 + i * 110, 193, names[i] + ": " + l, { a: "start", s: 12 })}`).join("")}</svg>`;
  })();
  const bitRow = (label, bits, y) => txt(10, y + 21, label, { a: "start", s: 13 }) + strip(bits.split("").map((b) => [b]), 80, y, { cw: 32, ch: 30 });
  const bitFig = (() => {
    const rows = [["Parent", "1011001010"], ["Child A", "1011001010"], ["Child B", "1011101010"], ["Child C", "1011001011"], ["Child D", "0010001110"]];
    const body = rows.map(([l, b], i) => (i === 0 ? bitRow(l, b, 8) : `<g data-pick="${l.slice(-1)}"><rect x="4" y="${46 + (i - 1) * 40}" width="402" height="36" rx="10" fill="var(--panel)" stroke="var(--line-2)" stroke-width="2"/>${bitRow(l, b, 49 + (i - 1) * 40)}</g>`)).join("");
    return `<svg viewBox="0 0 410 210" style="max-height:210px;max-width:430px">${body}</svg>`;
  })();
  B.add("l4-mutation", [
    { type: "pick", q: "A search is stuck on a local peak at 5, and the better peak is at 9. Each curve shows how far a Gaussian mutation with that σ is likely to move the gene (curves are scaled to the same height). Tap the one that gives the best chance of landing at the better peak in one mutation.", fig: gaussFig, a: "C", why: "At 9 (four units away) the σ = 0.3 and σ = 1.5 curves are essentially zero, while σ = 4 still has a real chance (about 6% to land within 0.5 of 9). The price: a wide curve rarely makes small, precise improvements. That is the trade-off between exploring and fine tuning." },
    { type: "multi", q: "Bit-flip mutation flips each bit independently with probability 1/L on an L-bit string. Which statements are true?", o: ["A child usually differs from its parent by about one bit on average", "Most children are exact copies of the parent, well over half", "Any bit string can in principle be reached from any parent in one step", "A child with 3 or more flips is rare, under 10% of children", "Raising the rate to 10/L keeps children very close to their parents"], a: [0, 2, 3], why: "The average number of flips is L × 1/L = 1. About 37% of children are exact copies and 37% have one flip, 18% have two, and 3 or more is only about 8%. In principle every string is reachable, just with a vanishing probability. A rate of 10/L would mean about 10 flips, so children would be far from the parent." },
    { type: "bug", q: "Gaussian mutation should nudge one gene a little. Tap the faulty line.", code: ["def mutate(parent, sigma):", "    child = parent[:]", "    i = random.randrange(len(child))", "    child[i] = random.gauss(0, sigma)", "    return child"], a: 3, why: "The gene is replaced by a fresh number near 0, wiping out its old value, which is a big jump rather than a nudge. It should add noise to the existing value: child[i] += random.gauss(0, sigma)." },
    { type: "pick", q: "Each bit of the parent is flipped independently with probability 1 in 10. Tap the child string that this mutation is MOST likely to produce (this exact string).", fig: bitFig, a: "A", hint: "Each unflipped bit has a 0.9 chance and each flipped bit has a 0.1 chance. Count how many bits differ from the parent.", why: "A is identical to the parent, so no bit flips: 0.9 to the power 10, about 35%. B and C each need one exact flip (about 3.9% each), and D differs in three bits (about 0.05%). A single specific string with fewer changes is always more likely under a low mutation rate, so staying put is the most common single outcome." },
    { type: "pick", q: "A hill climber tried four step sizes. Progress per mutation is the chance of an improvement multiplied by the average gain when it works. Tap the step size with the best progress.", fig: tbl(["Step size σ", "Chance a mutant is better", "Average gain when better"], [["0.01", "50%", "0.01"], ["0.1", "30%", "0.1"], ["1", "10%", "0.2"], ["10", "1%", "0.5"]], ["r1", "r2", "r3", "r4"]), a: "r2", hint: "Multiply the two columns: 50% of 0.01 is 0.005. 30% of 0.1 is 0.03.", why: "The products are 0.005, 0.03, 0.02 and 0.005. Tiny steps succeed often but gain almost nothing. Huge steps gain a lot but almost never succeed. The best step size sits in the middle, which is the idea behind adapting σ during a run." },
  ]);

  /* ---------- l4-crossover ---------- */
  const blockFig = (() => {
    const x0 = 50, cw = 50;
    const p1 = [0, 1, 1, 1, 0, 0, 0, 0], p2 = [0, 0, 0, 0, 0, 1, 1, 1];
    const row = (g, y, lab, good) => txt(8, y + 26, lab, { a: "start", s: 13 }) + g.map((v, i) => `<rect x="${x0 + 50 + i * cw}" y="${y}" width="${cw - 4}" height="${cw - 8}" rx="8" fill="${good.includes(i) ? "var(--teal)" : "var(--bg-2)"}" fill-opacity="${good.includes(i) ? ".85" : "1"}" stroke="var(--line-2)" stroke-width="2"/>${txt(x0 + 50 + i * cw + (cw - 4) / 2, y + 26, v, { c: good.includes(i) ? "#fff" : "var(--text)", s: 14 })}`).join("");
    const gaps = Array.from({ length: 7 }, (_, i) => `<g data-pick="g${i + 1}"><rect x="${x0 + 50 + (i + 1) * cw - 18}" y="112" width="26" height="36" rx="7" fill="var(--panel)" stroke="var(--line-2)" stroke-width="2"/>${txt(x0 + 50 + (i + 1) * cw - 5, 135, "g" + (i + 1), { s: 12, c: "var(--text-dim)" })}</g>`).join("");
    return `<svg viewBox="0 0 520 160" style="max-height:160px">${row(p1, 8, "P1", [1, 2, 3])}${row(p2, 58, "P2", [5, 6, 7])}${gaps}</svg>`;
  })();
  const cutKids = (() => {
    const kids = [["11000111", "k1"], ["00111100", "k2"], ["10100111", "k3"], ["11111100", "k4"]];
    return `<svg viewBox="0 0 440 215" style="max-height:215px;max-width:480px">${txt(8, 26, "P1", { a: "start" })}${strip("11111111".split("").map((c) => [c, "var(--blue)", "#fff"]), 70, 8, { cw: 34, ch: 28 })}${txt(8, 62, "P2", { a: "start" })}${strip("00000000".split("").map((c) => [c, "var(--amber)", "#fff"]), 70, 44, { cw: 34, ch: 28 })}${kids.map(([s, id], i) => `<g data-pick="${id}"><rect x="4" y="${82 + i * 33}" width="352" height="30" rx="8" fill="var(--panel)" stroke="var(--line-2)" stroke-width="2"/>${txt(30, 103 + i * 33, "Child " + (i + 1), { s: 12 })}${strip(s.split("").map((c) => [c]), 70, 84 + i * 33, { cw: 34, ch: 26 })}</g>`).join("")}</svg>`;
  })();
  B.add("l4-crossover", [
    { type: "slider", q: "1-point crossover on 8 genes picks one of the 7 gaps uniformly at random. About what percentage of the time are genes 3 and 4 (neighbours) split between the two parents?", min: 0, max: 100, step: 2, ans: 14, tol: 5, unit: "%", hint: "Genes 3 and 4 are split only if the cut is in the one gap between them. That is 1 gap out of 7.", why: "Only the single gap between genes 3 and 4 separates them: 1/7 ≈ 14%. Genes 1 and 8, at opposite ends, are split every time. This is positional bias: 1-point crossover keeps neighbours together, which helps when related genes sit next to each other and hurts when they do not." },
    { type: "pick", q: "Parent 1 has a good block (the three green genes). So does parent 2. Tap every cut gap where 1-point crossover (parent 1 before the cut, parent 2 after it) gives a child with BOTH good blocks.", fig: blockFig, a: ["g4", "g5"], why: "Genes 2 to 4 must come from parent 1, so the cut must be at gap g4 or later. Genes 6 to 8 must come from parent 2, so the cut must be at gap g5 or earlier. Only g4 and g5 satisfy both. Cuts inside a block, such as g2, g3, g6 and g7, break one." },
    { type: "match", q: "Match each operator to its trait.", pairs: [["1-point", "Keeps long runs of neighbouring genes together"], ["Uniform", "Any two genes are equally likely to be split"], ["2-point", "Swaps a block in the middle"], ["Mask of all 0s", "The child is a copy of parent 1"]], why: "A single cut leaves two long blocks. Uniform crossover tosses a coin per gene, so position does not matter. Two cuts swap the segment between them. A mask that never takes parent 2's genes just clones parent 1." },
    { type: "slider", q: "Two parents differ at exactly 3 of their 10 genes. How many different children can uniform crossover (a free choice of parent at every gene) produce?", min: 0, max: 16, step: 1, ans: 8, tol: 1, unit: " children", hint: "The 7 genes where the parents agree give no choice. Each of the 3 differing genes has 2 options: 2 × 2 × 2.", why: "Where parents agree, the child's gene is fixed. At each of the 3 differing genes it can come from either parent: 2³ = 8 children. Crossover can only recombine what the parents already have; it never creates a new gene value." },
    { type: "pick", q: "Parents are 11111111 and 00000000. Tap the child that cannot be made by 2-point crossover.", fig: cutKids, a: "k3", why: "2-point crossover cuts twice, so the source changes at most twice along the child. Child 3 (10100111) switches parent four times: 1, 0, 1, 0, 1 across the string. Child 1 changes twice, child 2 changes twice (a swapped middle) and child 4 changes once, which is a 2-point cut at the very end." },
  ]);

  /* ---------- l4-lab ---------- */
  const divFig = (() => {
    const cols = [["t = 1", 10, 99, "var(--teal)"], ["t = 3", 5, 112, "var(--blue)"], ["t = 30", 1, 135, "var(--rose)"]];
    const w = 520, h = 230;
    const body = cols.map(([l, d, b, c], i) => { const x = 60 + i * 150, bh = d * 11; return `<g data-pick="${l.replace(/\D/g, "")}"><rect x="${x - 10}" y="28" width="120" height="172" rx="12" fill="var(--panel)" stroke="var(--line-2)" stroke-width="2"/><rect x="${x + 10}" y="${170 - bh}" width="60" height="${bh}" rx="6" fill="${c}" fill-opacity=".85" stroke="var(--line-2)" stroke-width="2"/>${txt(x + 40, 164 - bh, "div " + d + "%", { s: 12 })}${txt(x + 40, 188, l, { s: 14 })}${txt(x + 40, 18, "best " + b + "/144", { s: 12, c: "var(--text-dim)" })}</g>`; }).join("");
    return `<svg viewBox="0 0 ${w} ${h}" style="max-height:${h}px">${body}${txt(260, 222, "Population of 30, after 600 evaluations (average of 10 runs)", { s: 11, c: "var(--text-faint)" })}</svg>`;
  })();
  B.add("l4-lab", [
    { type: "pick", q: "In the lab, algorithm 1 (steady-state, mutation only, population 30) was run with three tournament sizes. Diversity and best fitness after 600 evaluations are shown. Tap the setting that is most at risk of premature convergence.", fig: divFig, a: "30", why: "With t = 30 almost every pick is the current best, so diversity has fallen to 1%: the population is nearly all copies. Its best score is highest so far, but with no variety left only rare mutations can improve it, so on a harder target it would stall. t = 1 keeps variety but climbs slowly." },
    { type: "mcq", q: "These lab runs used algorithm 1 on the heart picture (144 pixels), typical runs, up to 20,000 evaluations. Why did the 0.05 run not reach 144?", fig: tbl(["Mutation per bit", "Flips per child", "Result"], [["0.0001", "0.01", "stuck at 135"], ["1/144", "1", "144 after about 3,000 evaluations"], ["0.05", "7.2", "stuck at 138"], ["0.2", "29", "stuck at 109"]]), o: ["A child flips about 7 bits, so it usually breaks more correct pixels than it fixes", "Seven flips per child means too few new pictures are tried, so exploration is poor", "A population of 30 is too small to hold the extra variety that this rate creates", "Tournament selection stops working as soon as the mutation rate passes 1 flip"], a: 0, why: "Near the end, only a few pixels are wrong, and each child flips about 7 random ones. Nearly every flip hits a correct pixel, so children are almost always worse and replace-worst rejects them. Rate 1/144 changes about one pixel, which is the right size of step. The tiny rate 0.0001 has almost no flips at all, and 0.2 is close to random." },
    { type: "match", q: "Match each lab setting to what you would see.", pairs: [["Population of 4", "Quick early gains, then variety runs out"], ["Tournament size 10 on 30 members", "Diversity line collapses almost at once"], ["Mutation 0.05 per bit", "Best creeps up but stays noisy and short of perfect"], ["Elites = 0 (generational)", "The best score can drop between generations"]], why: "A tiny population has too little variety to keep improving. A large tournament makes selection greedy, so copies of the best flood the population. A high mutation rate scrambles good pictures about as fast as it finds them. Without elites, the champion can be lost in a bad round." },
    { type: "bug", q: "This lab mutation should flip each pixel with probability pm (a small number). Tap the faulty line.", code: ["child = []", "for b in x:", "    if random() > pm:    # flip this pixel", "        b = 1 - b", "    child.append(b)"], a: 2, why: "random() > pm is true most of the time (about 99% for a small pm), so nearly every pixel flips and the child is the photo-negative of the parent. It should be random() < pm." },
    { type: "cat", q: "Which knob change would you try for each dashboard symptom in the lab?", buckets: ["Lower selection pressure or raise mutation", "Raise selection pressure"], items: [["Diversity hit 0 at generation 40 while the best sits at 0.92", 0], ["The mean is far below the best and has not moved in 200 generations", 1], ["Best, mean and diversity all stay flat, with a wide spread of members", 1], ["All 30 thumbnails look identical, 6 pixels wrong", 0], ["Every run converges to a different wrong picture", 0]], why: "Identical members (diversity near 0) mean selection is too strong: soften it or add mutation to get variety back. Lots of variety but no progress means selection is too weak to exploit what it has found. Different wrong pictures every run are a sign of early convergence in each run, so look at loosening pressure as well." },
  ]);
})();
