/* Data Science boss quizzes for Lectures 2 and 3. New scenarios: a recipe-sharing app (Forkful) and a bike-rental telemetry store (Pedalo). */
(function () {
  const N = NIC;

  N.registerBoss({
    id: "ds2-boss", subject: "ds", lecture: 2, title: "Lecture 2 boss quiz",
    blurb: "Nine questions set in a recipe-sharing app: data models, schema, graphs and NoSQL.",
    lede: "A new scenario: <b>Forkful</b>, a recipe-sharing app. Pick the right data model and NoSQL family for each part of it.",
    qs: [
      { type: "cat", q: "Which data model is the most natural first choice for each Forkful feature?",
        buckets: ["Document", "Relational tables", "Graph"],
        items: [["A recipe page: title, ingredients and steps, always read together and owned by one recipe", 0], ["Which cooks follow which, used to suggest cooks that friends of friends follow", 2], ["Ingredient suppliers shared by thousands of recipes and updated in one place", 1], ["A cook's saved collection: a nested list of notes, tags and photos, read as one unit", 0]],
        why: "Self-contained trees read whole suit documents. Shared data referenced by many records suits tables and joins. Relationships that you walk suit a graph." },
      { type: "multi", q: "Which are genuine advantages of storing Forkful's recipes as documents? Select all that apply.",
        o: ["Recipes can differ in shape without altering a schema", "A whole recipe is read from one place", "Documents map closely to the app's recipe objects", "Many-to-many links between recipes and cooks are simple joins", "The database rejects any recipe missing a field"], a: [0, 1, 2],
        why: "Flexibility, locality and a close match to objects are the document advantages. Joins across many-to-many links are the relational strength, and strict rejection is schema enforcement." },
      { type: "mcq", q: "A cook renames their display name. 1,200 recipe documents embed that name, whereas a relational design stores it once and points to it. How many stored items must change in each design?",
        o: ["Document: 1,200. Relational: 1", "Document: 1. Relational: 1,200", "Both: 1,200", "Both: 1"], a: 0,
        why: "Shared data referenced once is a single update. Copies embedded in documents must all be rewritten, and any missed copy shows a stale name." },
      { type: "mcq", q: "Forkful stores each recipe as a 2 MB document with big photo data inside. The recipe list page only needs each recipe's title. What is the downside of document locality here?",
        o: ["All 2 MB load for one title", "The title cannot be read from a document at all", "Documents are unable to hold photo data of any size", "Every single title needs its own separate join"], a: 0,
        why: "Documents are stored and loaded as one unit, so a small need on a large document wastes work." },
      { type: "mcq", q: "Forkful adds a new cook field: \"first name\" and \"last name\" instead of one \"name\". Old documents still have only \"name\". What does schema-on-read let the team do?",
        o: ["Split old names in the app on read", "Wait until a full migration of every document finishes", "Delete every old document and ask cooks to sign up again", "Rebuild every index across the database first of all"], a: 0,
        why: "Structure is interpreted when the application reads, so old and new shapes can coexist and be upgraded gradually." },
      { type: "match", q: "Match each NoSQL family to what defines it.",
        pairs: [["Key-value", "Items found by a partition key plus a sort key"], ["Document", "Collections of self-contained JSON-like records"], ["Wide-column", "Tables whose columns can vary from row to row"], ["Graph", "Vertices joined by labelled edges"]],
        why: "Key-value stores use composite keys, document stores group JSON-like documents into collections, wide-column stores allow per-row column sets, and graph stores are vertices and edges." },
      { type: "cat", q: "Modern databases are converging. Is each capability a <b>document-style feature added to a relational database</b>, or a <b>relational-style feature added to a document database</b>?",
        buckets: ["Document feature in relational", "Relational feature in document"],
        items: [["A JSON column you can index and query inside", 0], ["Joining two collections together on a shared field", 1], ["An XML column type that supports querying", 0], ["Looking up related records in another collection during a query", 1]],
        why: "JSON and XML support in relational engines (PostgreSQL, MySQL) is a document feature moving in. Joins across collections (RethinkDB) is a relational feature moving in." },
      { type: "mcq", q: "Forkful wants to show \"cooks you may know\" by hopping from a cook to their followers, then to those followers' other follows, and again. Which model makes these hops direct?",
        o: ["A graph, since each vertex lists its edges", "One big document per cook containing everyone else", "A text file scanned for every hop", "A key-value store with one value per cook"], a: 0,
        why: "A vertex knows its incoming and outgoing edges, so each hop is direct. Documents and flat lookups turn every hop into extra queries." },
      { type: "mcq", q: "Which set of goals describes what NoSQL databases put first?",
        o: ["Simple design, horizontal scaling and availability", "A single rigid schema, vertical scaling and full joins", "Manual sharding, fixed columns and offline batches", "Strict normalisation and stored procedures"], a: 0,
        why: "NoSQL focuses on simplicity, scaling out across machines and availability, and it usually relaxes a rigid schema." },
    ],
  });

  N.registerBoss({
    id: "ds3-boss", subject: "ds", lecture: 3, title: "Lecture 3 boss quiz",
    blurb: "Nine questions set in a bike-rental telemetry store: logs, hash indexes, compaction and SSTables.",
    lede: "A new scenario: <b>Pedalo</b>, a bike-rental app that records lock, unlock and battery events. Choose how to store and find them.",
    qs: [
      { type: "cat", q: "Which workload does each Pedalo job put on the database?",
        buckets: ["Transactional (write-heavy)", "Analytics (read-heavy)"],
        items: [["Record every unlock and lock event the moment it happens", 0], ["Work out which docks are empty most evenings across a year of data", 1], ["Log each battery reading from thousands of bikes each minute", 0], ["Build a monthly report of average trip length by area", 1]],
        why: "Many small incoming writes are transactional. Scanning large amounts of history to answer a question is analytics." },
      { type: "mcq", q: "Pedalo starts with a plain log: every event is appended to a file, and a lookup scans the whole file. It holds 5 million events today and will hold 50 million next year. How will a lookup change?",
        o: ["About ten times slower", "About the same speed", "About a hundred times slower", "About ten times faster"], a: 0,
        why: "A full scan touches every record, so time grows in proportion to the data: ten times the events means about ten times the scan." },
      { type: "multi", q: "Beyond appending lines, which of these does a real log-based store have to deal with? Select all that apply.",
        o: ["Marking deleted keys without rewriting the file", "Recovering after a crash halfway through a write", "Two writers appending at the same time", "Renaming every key to be shorter", "Converting the file to plain text for speed"], a: [0, 1, 2],
        why: "Tombstones, crash recovery (including partially written records) and concurrency control are real concerns. Shorter keys are not required, and binary formats are normally more efficient than plain text." },
      { type: "mcq", q: "A hash index on Pedalo's log maps each bike id to a byte offset. What is the biggest limit of this design?",
        o: ["All the keys must fit in memory", "Reads need a full scan of the log", "Writes need random access on disk", "Old values are overwritten in place"], a: 0,
        why: "The map lives in RAM, so the design only works while every key fits there. Reads are single jumps and writes are sequential appends." },
      { type: "mcq", q: "A bike's battery counter is overwritten 500,000 times while there are only 800 bikes. After compaction, roughly how many records remain per bike?",
        o: ["One", "About 500", "About 5,000", "As many as before"], a: 0,
        why: "Compaction keeps just the latest value per key, so each bike ends up with one record." },
      { type: "order", q: "Put the SSTable write path in the right order.",
        items: ["A write arrives and is added to the in-memory sorted tree", "The tree grows large enough to be written out", "It is saved to disk as a new sorted segment, the newest one", "A background job later merges and compacts old segments"],
        why: "Writes land in the memtable first, a full memtable is flushed as a sorted SSTable, and old segments are merged in the background." },
      { type: "match", q: "Match each structure to its role.",
        pairs: [["Tombstone", "Marks a key as deleted until compaction drops it"], ["Memtable", "In-memory sorted tree that absorbs new writes"], ["Sparse index", "Offsets for only some keys of a sorted segment"], ["Compaction", "Keeps the latest value per key, dropping older copies"]],
        why: "Each piece has one job: delete marker, write buffer, cheap partial index, and space reclaimer." },
      { type: "bug", q: "This describes how a store answers a read. Which step is in the wrong order?",
        code: ["1. Look in the memtable first", "2. Then look in the oldest on-disk segment", "3. Then look in the next newer segment", "4. Stop at the first place that has the key"], a: 1,
        why: "Newer data must win, so the search goes memtable, then the newest segment, then older ones. Starting with the oldest segment could return an out-of-date value." },
      { type: "mcq", q: "Pedalo needs to fetch every trip whose id falls between two given ids, in order. Which store handles this best?",
        o: ["Sorted segments (SSTables)", "A hash index over the log", "A log with no index", "A cache holding only the newest trip"], a: 0,
        why: "Keys sorted on disk allow a range read: jump to the start and read forward. A hash map has no ordering, so ranges are inefficient." },
    ],
  });
})();
