(function () {
  const B = NIC.bank;

  B.add("a7-entropy", [
    {
      type: "match",
      q: "An event happens with the chance shown. Match each chance to the surprise it carries when it happens.",
      pairs: [
        ["1 in 2", "1 bit"],
        ["1 in 4", "2 bits"],
        ["1 in 16", "4 bits"],
        ["1 in 64", "6 bits"],
      ],
      hint: "Count how many times you halve 1 to reach the chance: 1/2 is one halving, 1/4 is two.",
      why: "Surprise is −log₂ p, which counts the halvings. 1/2 is one halving, 1/4 is two, 1/16 is four (2⁴ = 16) and 1/64 is six (2⁶ = 64). Each halving of the chance adds exactly one bit.",
    },
    {
      type: "slider",
      q: "A source sends one of five symbols. Symbol A has chance 1/2 and each of the other four has chance 1/8. Surprise: A carries 1 bit, each other symbol carries 3 bits. What is its entropy in bits per symbol?",
      min: 0,
      max: 3,
      step: 0.25,
      start: 1,
      ans: 2,
      tol: 0.25,
      unit: " bits",
      hint: "A adds 1/2 × 1 = 0.5. The four rare symbols add 4 × (1/8 × 3) = 1.5.",
      why: "Entropy averages the surprise, weighted by chance: 0.5 × 1 + 4 × (0.125 × 3) = 0.5 + 1.5 = 2 bits. That is below the 2.32 bits (log₂ 5) of five equally likely symbols, because the skew towards A makes the source more predictable.",
    },
    {
      type: "cat",
      q: "Each event is a fair draw. Sort them by how much surprise they carry when they happen. Three bits of surprise means a 1 in 8 chance.",
      buckets: ["At most 3 bits", "More than 3 bits"],
      items: [
        ["Heads on a fair coin", 0],
        ["A six on a fair six-sided die", 0],
        ["A named suit from a shuffled pack", 0],
        ["One named card from a shuffled pack of 52", 1],
        ["One named day of a 365-day year", 1],
        ["A named number picked from 1 to 100", 1],
      ],
      hint: "Rarer than 1 in 8 means more than 3 bits. A die gives 1 in 6, which is likelier than 1 in 8.",
      why: "Heads is 1 bit, a six is 1 in 6 (about 2.6 bits) and a suit is 1 in 4 (2 bits), all at most 3. A single card is 1 in 52, a day is 1 in 365 and a number from 100 is 1 in 100, so each is rarer than 1 in 8 and carries more than 3 bits.",
    },
    {
      type: "order",
      q: "Put the steps of working out a source's entropy in order.",
      items: [
        "List each symbol's chance of appearing",
        "Turn each chance into a surprise, −log₂ p",
        "Multiply each surprise by that symbol's own chance",
        "Add the results to get bits per symbol",
      ],
      hint: "You need the chances before you can find any surprise, and you weight before you add.",
      why: "Entropy is the average surprise. Each symbol's surprise is found from its chance, weighted by how often it occurs, and then the weighted values are summed. Adding unweighted surprises would treat a rare symbol as if it turned up as often as a common one.",
    },
    {
      type: "multi",
      q: "Select every statement about entropy that is true.",
      o: [
        "Adding a symbol that never occurs leaves the entropy unchanged",
        "Renaming the symbols without changing their chances leaves it unchanged",
        "Three equally likely symbols have an entropy below 2 bits",
        "A more predictable source has a higher entropy",
        "Two sources with five symbols each always have equal entropy",
      ],
      a: [0, 1, 2],
      hint: "Entropy depends on the chances only. Which numbers does a symbol that never occurs add to the sum?",
      why: "Only the chances matter, so renaming changes nothing and a symbol with chance 0 adds nothing. Three equal symbols give log₂ 3 ≈ 1.58 bits, below 2. Predictable sources have lower entropy, and equal alphabet size says nothing about equal chances.",
    },
    {
      type: "bug",
      q: "This function should return the entropy in bits of a list of chances. For a fair four-sided die it returns about 1.39 instead of 2. Click the faulty line.",
      code: ["def entropy(probs):", "    h = 0", "    for p in probs:", "        h -= p * math.log(p)", "    return h"],
      a: 3,
      hint: "math.log is the natural logarithm. Which logarithm gives bits?",
      why: "math.log uses base e, so the answer is in nats: 4 × 0.25 × ln 4 ≈ 1.39. Bits need base 2, so the line should call math.log2(p). The weighting and the sign are already right.",
    },
  ]);

  B.add("a7-huffman", [
    {
      type: "slider",
      q: "A message of 16 symbols has counts A 8, B 4, C 2, D 1 and E 1. Huffman gives A a 1-bit code, B 2 bits, C 3 bits, and D and E 4 bits each. How many bits does the whole message take?",
      min: 16,
      max: 48,
      step: 2,
      start: 24,
      ans: 30,
      tol: 2,
      unit: " bits",
      hint: "8 × 1 = 8, 4 × 2 = 8, 2 × 3 = 6, then 1 × 4 twice = 8. Add the four numbers.",
      why: "Each symbol costs its count times its codeword length: 8 + 8 + 6 + 4 + 4 = 30 bits. Plain 3-bit codes for five symbols would cost 48 bits, so the skew in the counts is what Huffman exploits.",
    },
    {
      type: "cat",
      q: "Huffman builds a code for each set of chances. Sort the sets by whether every symbol ends up with a codeword of the same length.",
      buckets: ["All the same length", "Different lengths"],
      items: [
        ["Four symbols at 1/4 each", 0],
        ["Eight symbols at 1/8 each", 0],
        ["Two symbols at 1/2 each", 0],
        ["Chances 1/2, 1/4, 1/8 and 1/8", 1],
        ["Chances 0.4, 0.3, 0.2 and 0.1", 1],
        ["Chances 0.7, 0.1, 0.1 and 0.1", 1],
      ],
      hint: "When every chance is equal, every merge pairs equals, so the tree comes out perfectly balanced.",
      why: "Equal chances give a balanced tree, so 4 symbols get 2 bits, 8 get 3 and 2 get 1. A skewed set always leaves some symbols rarer than others, and Huffman pushes the rare ones deeper, so the lengths differ.",
    },
    {
      type: "match",
      q: "Match each idea from Huffman coding to what it means.",
      pairs: [
        ["Prefix-free", "No codeword is the start of another, so no separators are needed"],
        ["Greedy choice", "Merge the two rarest nodes, which pushes them deepest"],
        ["The queue", "Holds leaves and merged nodes, sorted by weight"],
        ["L ≥ H", "Average length never beats the entropy"],
      ],
      hint: "Think about what each term does in the algorithm.",
      why: "A prefix-free code can be read left to right without separators. The greedy step merges the two lowest weights, since the deepest places should cost the rarest symbols. Merged nodes rejoin the queue as if they were symbols. Entropy is a floor that whole-bit codewords can approach but not undercut.",
    },
    {
      type: "multi",
      q: "A Huffman code is built for some symbol counts. Select every statement that must be true.",
      o: [
        "The two rarest symbols get codewords of the same length",
        "The most frequent symbol always gets a 1-bit codeword",
        "Swapping every 0 and 1 in all codewords gives a code with the same average length",
        "A rarer symbol can get a shorter codeword than a commoner one",
        "The average codeword length is never below the entropy",
      ],
      a: [0, 2, 4],
      hint: "Test the second statement on four equally likely symbols.",
      why: "The two rarest are merged first, so they sit together at the bottom of the tree with equal lengths. Swapping 0 and 1 only relabels branches, so the lengths stay put. No code can beat entropy on average. With four equal symbols the commonest gets 2 bits, not 1, and swapping a rare symbol above a common one would only raise the cost.",
    },
    {
      type: "bug",
      q: "This function should return the average codeword length for a code, where code maps each symbol to its bit string and probs maps each symbol to its chance. For chances 1/2, 1/4, 1/4 and lengths 1, 2, 2 it should return 1.5 but it returns 5. Click the faulty line.",
      code: [
        "def avg_length(code, probs):",
        "    total = 0",
        "    for sym in code:",
        "        total += len(code[sym])",
        "    return total",
      ],
      a: 3,
      hint: "An average must weight each length by how often the symbol occurs.",
      why: "The line adds up the raw lengths, 1 + 2 + 2 = 5, so a rare symbol counts as much as a common one. It should add probs[sym] * len(code[sym]), giving 0.5 + 0.5 + 0.5 = 1.5.",
    },
    {
      type: "mcq",
      q: "Symbols A, B, C and D have counts 1, 1, 2 and 2. After merging the two 1s into a 2, three nodes of weight 2 are tied. Whichever tied pair merges next, two different valid Huffman trees can result What does this tell you about the two trees?",
      o: [
        "Both are optimal, same total",
        "The wider tree is always the cheaper one",
        "The taller tree is always the cheaper one",
      ],
      a: 0,
      hint: "Try each: the first tree has all lengths 2, the second has lengths 1, 2, 3 and 3.",
      why: "Ties give different shapes but the same cost. All lengths 2 costs 2 × (1 + 1 + 2 + 2) = 12 bits. Lengths 1, 2, 3 and 3 for the counts 2, 2, 1 and 1 cost 2 + 4 + 3 + 3 = 12. Huffman guarantees the minimum total, not one unique tree.",
    },
  ]);

  B.add("a7-lzw", [
    {
      type: "match",
      q: "The decoder starts with A = 0 and B = 1 and rebuilds the table as it reads. Match each stream of codes to the text it decodes to.",
      pairs: [
        ["0, 1, 2, 0", "ABABA"],
        ["1, 0, 2, 4", "BABABAB"],
        ["0, 2, 3", "AAAAAA"],
        ["0, 1, 3, 2", "ABBBAB"],
      ],
      hint: "Add a new entry after each code: the previous output plus the first letter of the current one. A code one past the table is previous output plus its own first letter.",
      why: "For 0, 1, 2, 0: A, B (add AB = 2), AB (add BA = 3), A, giving A B AB A. For 1, 0, 2, 4: B, A (BA = 2), BA (AB = 3), then 4 is missing so it is BA + B = BAB. For 0, 2, 3: A, then 2 is missing so it is A + A = AA, then 3 is missing so it is AA + A = AAA, giving A AA AAA. For 0, 1, 3, 2: A, B (AB = 2), 3 is missing so B + B = BB, then AB.",
    },
    {
      type: "cat",
      q: "A decoder started with A = 0 and B = 1 and has built entries up to code 4, so its table holds codes 0 to 4. A new code arrives. Sort each one by what the decoder finds.",
      buckets: ["Already in the table", "Missing-entry case", "Corrupt stream"],
      items: [
        ["Code 1", 0],
        ["Code 4", 0],
        ["Code 5", 1],
        ["Code 6", 2],
        ["Code 9", 2],
      ],
      hint: "The decoder can handle exactly one code past its table: the one it is about to create.",
      why: "Codes 0 to 4 are already known. Code 5 is the next free slot, which is the case where the encoder used an entry the instant it made it, so the decoder rebuilds it as the previous output plus its own first letter. Anything beyond that could never have been made, so the stream is corrupt.",
    },
    {
      type: "slider",
      q: "An encoder starts with 4 single letters in its dictionary (codes 0 to 3). It adds one new entry each time it sends a code, except for the very last code. A message produces 9 codes. How many entries does the dictionary hold at the end?",
      min: 4,
      max: 20,
      step: 1,
      start: 8,
      ans: 12,
      tol: 0,
      unit: " entries",
      hint: "9 codes sent, but the last one adds nothing. So 8 new entries on top of the 4 letters.",
      why: "Every emit except the final one adds a new entry, so 9 codes add 8 entries: 4 + 8 = 12. The final emit has no next letter to extend the phrase, so it creates nothing.",
    },
    {
      type: "order",
      q: "Put one round of the LZW encoder in order.",
      items: [
        "Find the longest phrase w that is already in the dictionary",
        "Send the dictionary code for w",
        "Add w plus the next letter as a new entry",
        "Start the next phrase from that next letter",
      ],
      hint: "You can only add the next letter's phrase once you know where w stops.",
      why: "The encoder grows w until w plus one more letter is unknown. It sends w's code, records the new phrase so it can be reused later, and carries on from the letter that did not fit. The decoder can follow the same steps because each new entry depends only on text it has already seen.",
    },
    {
      type: "bug",
      q: "This LZW encoder should send the code of the longest known phrase w whenever w plus the next letter is new. Instead it crashes with a KeyError at the first new phrase. Click the faulty line.",
      code: [
        "def lzw(text, alphabet):",
        "    d = {ch: i for i, ch in enumerate(alphabet)}",
        '    w, out = "", []',
        "    for c in text:",
        "        if w + c in d:",
        "            w = w + c",
        "        else:",
        "            out.append(d[w + c])",
        "            d[w + c] = len(d)",
        "            w = c",
        "    out.append(d[w])",
        "    return out",
      ],
      a: 7,
      hint: "At that point w + c is new, so it is not in the dictionary yet. Which phrase is known?",
      why: "In the else branch w + c is the new phrase, which is not in the dictionary yet, so looking it up fails. The encoder must send the code of the known phrase w, out.append(d[w]), and only then add w + c.",
    },
    {
      type: "mcq",
      q: "A decoder reads codes with the alphabet A = 0, B = 1 and C = 2 and gets 0, 1, 2, 3, 5. What text does it produce?",
      o: ["ABCABCA", "ABCABCB", "ABCCABA"],
      a: 0,
      hint: "After each code add previous output plus the first letter of the current one.",
      why: "0 gives A, 1 gives B (add AB = 3), 2 gives C (add BC = 4), 3 gives AB (add CA = 5), and 5 gives CA (add ABC = 6). Joined, that is A B C AB CA = ABCABCA.",
    },
  ]);

  B.add("a8-hash", [
    {
      type: "cat",
      q: "A hash chain stores in each block the hash of the one before it. Sort each action by whether a checker that only follows those links would notice it.",
      buckets: ["Noticed by the links", "Not noticed by the links"],
      items: [
        ["Block 1's data is edited and nothing else is touched", 0],
        ["Block 2's stored prev value is changed to a made-up one", 0],
        ["A middle block is deleted and the gap is left as it is", 0],
        ["Block 1 is edited, then every later hash and prev is recomputed", 1],
        ["The newest block is edited and its own hash is recomputed", 1],
        ["Someone with full write access rebuilds the whole chain", 1],
      ],
      hint: "A link only breaks if something is left pointing at a value that no longer exists.",
      why: "Editing alone, forging a prev or deleting a block leaves some later block pointing at a hash that no longer exists, so a link breaks. If the attacker fixes every later hash, or edits the newest block that nothing points back to, everything is consistent again. Chains make edits evident but cannot stop a careful rewrite.",
    },
    {
      type: "match",
      q: "Match each fact about hashing and mining to the reason behind it.",
      pairs: [
        ["Changing one letter of a block", "Gives a completely different hash"],
        ["Finding a winning nonce", "Only trial and error works, one hash per try"],
        ["Checking a winning nonce", "One hash, whatever the difficulty"],
        ["Rebuilding a chain after an edit", "Looks consistent, so links alone cannot prevent it"],
      ],
      hint: "Think about which side of proof of work is hard and which is cheap.",
      why: "A tiny change gives a totally different digest. Mining has no shortcut, so miners keep trying nonces, while anyone can verify an answer with a single hash. A rebuilt chain is self-consistent, so link checks cannot tell it from the original: detecting tampering is not the same as preventing it.",
    },
    {
      type: "slider",
      q: "On a miner's laptop, finding a hash that starts with 2 hex zeros takes about 2 seconds. Each extra zero multiplies the work by 16. About how many minutes would 4 hex zeros take?",
      min: 0,
      max: 30,
      step: 1,
      start: 2,
      ans: 8.5,
      tol: 1.5,
      unit: " min",
      hint: "Two more zeros is 16 × 16 = 256 times the work. 2 seconds × 256 is about 500 seconds.",
      why: "Two more zeros means 16 × 16 = 256 times the tries, so 2 × 256 = 512 seconds, which is about 8.5 minutes. Difficulty grows exponentially with the number of required zeros.",
    },
    {
      type: "order",
      q: "Put what a checker sees after someone edits block 1 in order.",
      items: [
        "The attacker changes the data inside block 1",
        "Recomputing block 1's hash now gives a different value",
        "Block 2's stored prev no longer matches that value",
        "The checker flags the chain as broken from block 2 on",
      ],
      hint: "Each step follows from the one before it, and the checker needs the hash to differ before it can see the mismatch.",
      why: "The edit changes block 1's hash, and block 2 still holds the old hash as its prev. The checker compares the two, sees the mismatch and rejects the chain from that point. The attacker would then have to redo block 2 and every block after it.",
    },
    {
      type: "multi",
      q: "Select every statement about proof of work that is true.",
      o: [
        "Checking a winning nonce takes one hash, however hard the puzzle",
        "One extra required hex zero multiplies the expected tries by 16",
        "A nonce that wins for one block also wins for the next block",
        "Higher difficulty makes checking 16 times slower per zero",
        "A lucky miner can find a winning nonce on the first try",
      ],
      a: [0, 1, 4],
      hint: "Each block has different contents, so it has a different hash for every nonce.",
      why: "Verification is one hash at any difficulty, and each extra zero cuts the chance of success per try 16-fold. Mining is a lottery, so a lucky try can win at once. A nonce only suits the exact block it was found for, since changing any block data changes its hash.",
    },
    {
      type: "bug",
      q: "This miner should keep trying nonces until the block's hash starts with the required number of zeros. Asked for 4 zeros, it stops after about 16 tries with a hash that often has just one. Click the faulty line.",
      code: [
        "def mine(block, zeros):",
        "    block.nonce = 0",
        '    while not hash_of(block).startswith("0"):',
        "        block.nonce += 1",
        "    return block.nonce",
      ],
      a: 2,
      hint: "Which line should use the zeros value, and does it?",
      why: 'The test only asks for one leading zero, whatever zeros says, and one hex zero turns up about once in 16 tries. The loop should test startswith("0" * zeros), so that 4 zeros need about 65,536 tries on average.',
    },
  ]);
})();
