"""Regenerate vendor/fluent-emoji.js from Microsoft Fluent Emoji (Flat), via the Iconify JSON package.

Usage:  python tools/emoji-build.py
To add an emoji: add  "<the emoji character(s)>": "<fluent-emoji-flat icon name>"  to MAP below and rerun.
Names: https://icon-sets.iconify.design/fluent-emoji-flat/  (e.g. "fire", "brain", "chart-increasing").
"""
import json, os, urllib.request

MAP = {
    "🧬": "dna", "🧠": "brain", "🐜": "ant", "💥": "collision", "📬": "open-mailbox-with-raised-flag",
    "🎩": "top-hat", "✂": "scissors", "✈": "airplane", "🔁": "repeat-button", "🐞": "lady-beetle",
    "💀": "skull", "🚐": "minibus", "🚚": "delivery-truck", "📈": "chart-increasing", "🤖": "robot",
    "🎯": "bullseye", "🐒": "monkey", "🦎": "lizard", "🚗": "automobile", "📡": "satellite-antenna",
    "📅": "calendar", "💧": "droplet", "🥾": "hiking-boot", "🔥": "fire", "⚠": "warning",
    "🇬🇧": "crown", "🇺🇸": "statue-of-liberty",  # Fluent has no flags: London / New York stand-ins
}
URL = "https://cdn.jsdelivr.net/npm/@iconify-json/fluent-emoji-flat@1/icons.json"
OUT = os.path.join(os.path.dirname(__file__), "..", "vendor", "fluent-emoji.js")

data = json.load(urllib.request.urlopen(URL))
W, H = data.get("width", 32), data.get("height", 32)
svgs = {}
for name in sorted(set(MAP.values())):
    ic = data["icons"][name]
    svgs[name] = f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="{ic.get("left", 0)} {ic.get("top", 0)} {ic.get("width", W)} {ic.get("height", H)}">{ic["body"]}</svg>'
with open(OUT, "w", encoding="utf-8") as f:
    f.write("/* Fluent Emoji (Flat) by Microsoft Corporation, MIT License. https://github.com/microsoft/fluentui-emoji\n"
            "   Generated by tools/emoji-build.py from @iconify-json/fluent-emoji-flat. Do not edit by hand. */\n")
    f.write("window.FLUENT_EMOJI = " + json.dumps({"map": MAP, "svg": svgs}, ensure_ascii=False) + ";\n")
print(f"wrote {OUT}: {len(svgs)} icons")
