/* Nature-Inspired boss quizzes for Lectures 5 and 6 — fresh scenarios, mixed formats. Every number verified by hand/node. */
(function () {
  const N = NIC;

  /* ================= Lecture 5 ================= */
  N.registerBoss({
    id: "l5-boss",
    lecture: 5,
    title: "Lecture 5 boss quiz",
    blurb: "Nine questions: pick encodings, spot broken operators and decode genomes in situations you haven't met.",
    lede: "A café rota, school clubs, a greenhouse and a repair routine. Use what you know about encodings, validity and direct versus indirect representations.",
    qs: [
      {
        type: "mcq",
        q: "A café plans its rota with a <b>permutation</b> chromosome: gene i is the barista working station i, and all 6 baristas are used once. Which mutation always keeps the rota valid?",
        o: [
          "Replace one gene with a barista chosen at random",
          "Swap the baristas at two stations",
          "Add a little noise to one gene",
          "Flip one bit of one gene",
        ],
        a: 1,
        why: "Swap only rearranges baristas already in the rota. Replacing a gene can put someone on two stations and leave another station empty; noise and bit flips don't even apply to this encoding.",
      },
      {
        type: "mcq",
        q: "A school must give each of its 9 clubs exactly one teacher, but a teacher can run several clubs. Which encoding <b>guarantees</b> every club has a teacher?",
        o: [
          "One gene per teacher, whose value is a club",
          "One gene per club, whose value is a teacher",
          "One bit per teacher and club pair, set to 1 if they are linked",
          "One gene per teacher, whose value is how many clubs they run",
        ],
        a: 1,
        why: "A gene per club always holds one teacher, so every club is covered exactly once. The other encodings can leave a club with nobody or with several teachers.",
      },
      {
        type: "multi",
        q: "Which statements about <b>indirect</b> encodings are true?",
        o: [
          "A decoder turns the genes into a solution",
          "The decoder can enforce constraints such as no clashes",
          "Neighbouring chromosomes may decode to quite different solutions",
          "Decoding is always quicker than reading a direct genotype",
          "A mutation can never affect more than one part of the solution",
        ],
        a: [0, 1, 2],
        why: "Indirect encodings hold instructions for a constructive heuristic, so they can bake in constraints but are slower to interpret and have rugged neighbourhoods. A single change can cascade through the decoder.",
      },
      {
        type: "slider",
        q: "A greenhouse has 5 vents, each set to one of 4 openings. About how many different settings does the controller's chromosome describe?",
        min: 0,
        max: 2000,
        step: 50,
        ans: 1024,
        tol: 150,
        unit: " settings",
        hint: "4 × 4 = 16. Then 16 × 16 = 256 (that's four vents). One more factor of 4.",
        why: "4⁵ = 1,024. Each of 5 genes has 4 values, so the counts multiply.",
      },
      {
        type: "order",
        q: "Order the steps of one-point crossover with repair on two tours.",
        items: [
          "Cut both parents after the same gene",
          "Join the head of one parent to the tail of the other",
          "Find the cities that appear twice in the child",
          "Find the cities that are missing from the child",
          "Replace the repeats with the missing cities",
        ],
        why: "Cut, swap tails, find the repeats, find what is missing, then repair. The child ends up a valid tour.",
      },
      {
        type: "match",
        q: "Match each operation to what it does.",
        pairs: [
          ["Single-gene mutation of a direct timetable", "Moves exactly one exam"],
          ["Changing one gene of an indirect timetable", "May shift several later exams"],
          ["Random-gene mutation on an ordered real vector", "Often breaks the ordering rule"],
          ["Mutating a variable-length nozzle genotype", "Always leaves a valid nozzle"],
        ],
        why: "Direct genes map one-to-one. Indirect decoders cascade. Ordered reals have rules that mutation can violate, while the nozzle's single rule (middle section smallest) is kept by construction.",
      },
      {
        type: "cat",
        q: "Direct or indirect? Sort each description.",
        buckets: ["Direct", "Indirect"],
        items: [
          ["The gene value is the exam's actual slot", 0],
          ["The gene value picks the k-th clash-free slot", 1],
          ["Fitness evaluation is fast because the genotype is easy to read", 0],
          ["Domain knowledge can shrink the search space a lot", 1],
          ["Effects of a mutation are easy to predict", 0],
          ["Neighbourhoods are highly rugged", 1],
        ],
        why: "Direct: simple map, smooth landscape, fast interpretation. Indirect: uses domain knowledge and can enforce constraints, at the cost of slow decoding and ruggedness.",
      },
      {
        type: "bug",
        q: "This routine should repair a child tour by replacing repeated cities with the missing ones. Click the faulty line.",
        code: [
          "def repair(child, parent):",
          "    seen = set()",
          "    missing = [c for c in parent if c in child]",
          "    for i, c in enumerate(child):",
          "        if c in seen:",
          "            child[i] = missing.pop(0)",
          "        seen.add(c)",
          "    return child",
        ],
        a: 2,
        why: "<code>missing</code> should list the cities of the parent that are <b>not</b> in the child. With <code>in</code> it lists cities the child already has, so the repair would insert more repeats.",
      },
      {
        type: "mcq",
        q: "A coordinate is stored as one sign bit and four magnitude bits, and currently reads <code>+0110</code> (that is +6). Which <b>single-bit flip</b> changes the value the most?",
        o: ["The sign bit", "The leftmost magnitude bit", "The second magnitude bit", "The rightmost bit"],
        a: 0,
        why: "Flipping the sign gives −6, a change of 12. The leftmost magnitude bit gives 1110 = 14, a change of 8; the second bit gives 0010 = 2, a change of 4; the rightmost gives 7, a change of 1.",
      },
    ],
  });

  /* ================= Lecture 6 ================= */
  N.registerBoss({
    id: "l6-boss",
    lecture: 6,
    title: "Lecture 6 boss quiz",
    blurb: "Nine questions: evaluate trees, spot what GP can and cannot find, and track subtree operators.",
    lede: "Programs as trees, depth limits, crossover bookkeeping and the five preparatory choices.",
    qs: [
      {
        type: "mcq",
        q: "You evolve a formula that predicts a plant's height from its age. Which is the best <b>fitness</b> for a candidate formula?",
        o: [
          "The sum of its absolute errors over many ages",
          "Its error on the first age in the data only",
          "The number of nodes in its tree, fewer being better",
          "The depth of its tree",
        ],
        a: 0,
        why: "Fitness in GP means running the program on many test inputs and adding up the errors. One input could be lucky, and size or depth say nothing about accuracy.",
      },
      {
        type: "mcq",
        q: "Evaluate <code>(* (+ X 1) (IF (&gt; X 2) 4 5))</code> for X = 3. (IF returns its second argument when the test is true, otherwise its third.)",
        o: ["12", "16", "17", "20"],
        a: 1,
        hint: "Work from the leaves up: X + 1 first, then the IF.",
        why: "X + 1 = 4. The test 3 &gt; 2 is true, so IF gives 4. Then 4 × 4 = <b>16</b>.",
      },
      {
        type: "mcq",
        q: "Maximum depth is 4 and the root is at depth 1. A function node at depth 3 is expanded. What must its children be?",
        o: ["Terminals only", "Functions only", "A mix, chosen at random", "Nothing: it stays childless"],
        a: 0,
        why: "Depth 3 = Max − 1, so its children land on the last allowed level (depth 4) and must be terminals.",
      },
      {
        type: "slider",
        q: "A full binary tree has 31 nodes. Roughly what percentage of them are leaves?",
        min: 0,
        max: 100,
        step: 5,
        ans: 50,
        tol: 10,
        unit: "%",
        hint: "A full binary tree of depth 5 has 16 nodes on its bottom level.",
        why: "16 leaves out of 31 nodes is about 52%. That's why a randomly chosen node usually sits at the bottom of the tree.",
      },
      {
        type: "mcq",
        q: "Subtree crossover: parent A has 9 nodes and parent B has 13. A's chosen subtree has 4 nodes and B's has 2. What are the children's sizes?",
        o: ["5 and 17", "7 and 15", "9 and 13", "11 and 11"],
        a: 1,
        why: "Child 1 is 9 − 4 + 2 = 7. Child 2 is 13 − 2 + 4 = 15. The total, 22, doesn't change.",
      },
      {
        type: "order",
        q: "Order one generation of a GP run.",
        items: [
          "Run every program on the test inputs",
          "Compute each program's error",
          "Select parents using fitness",
          "Apply subtree crossover and mutation",
          "Check whether a program meets the stop rule",
        ],
        why: "Run, score, select, vary, then test the termination criterion. If nothing meets it the loop repeats.",
      },
      {
        type: "cat",
        q: "Which preparatory step does each decision belong to?",
        buckets: ["Terminal set", "Function set", "Fitness measure"],
        items: [
          ["Allow random constants in the leaves", 0],
          ["Include protected division", 1],
          ["Use the sum of absolute errors", 2],
          ["Provide the input variable X", 0],
          ["Allow IF with four children", 1],
          ["Average the error over 40 test points rather than 11", 2],
        ],
        why: "Terminals are the leaves (inputs and constants); functions are the internal nodes; the fitness measure says how programs are scored.",
      },
      {
        type: "mcq",
        q: "A student runs GP with functions {+, −} and terminals {X, 2} to find 3X² + 1. It never succeeds, however large the population. Why?",
        o: [
          "No tree built from + and − can contain X × X",
          "The population is too large for tournament selection",
          "The random constants are too big",
          "Protected division is missing",
        ],
        a: 0,
        why: "Adding and subtracting X and 2 only gives straight lines a·X + b. The sets are not rich enough to build the target, so evolution has nothing to find.",
      },
      {
        type: "match",
        q: "Match each GP term to its job.",
        pairs: [
          ["Function set", "Operations such as +, × and IF at internal nodes"],
          ["Terminal set", "Inputs and constants at the leaves"],
          ["Fitness measure", "Error summed over many test cases"],
          ["Termination criterion", "Stop when the error is below a threshold"],
        ],
        why: "These are four of the five preparatory steps (the fifth is the run parameters, such as population size).",
      },
    ],
  });
})();
